### ISSUE TITLE
RTCPeerConnection and getStats

### ISSUE THREAD

**Issue by ghenry** [flutter-webrtc/dart-sip-ua#124]
Hi all,

How can I get a current video or audio call RTCPeerConnection object?

I see it at:

https://github.com/flutter-webrtc/dart-sip-ua/blob/62beb1ac2502e41289ddadcce243022ae1d1bdd9/lib/src/rtc_session.dart#L87

as I want to do (excuse messy `Logger()`, not put that in a controller yet) this in my call screen (again, for testing)

```
  void _getAudioStats(MediaStream _localStream, RTCPeerConnection _peerConnection) async {
    if (_localStream != null || _peerConnection != null) {
      var logger = Logger();
      logger.d(await _peerConnection.getStats(_localStream.getAudioTracks()[0]));
    }
  }
```

for testing.

**Comment by ghenry** [comment]
Sound OK?

**Comment by ghenry** [comment]
`Future<List<StatsReport>> getStats([MediaStreamTrack track]);`

is what I'm after.

**Comment by cloudwebrtc** [comment]
hey @ghenry ,I have exposed PeerConnection from Call, I think we can get stats from pc
https://github.com/flutter-webrtc/dart-sip-ua/commit/26574cfa0e95425929fa57ff2d12b148176af434#diff-e2fa6b196d5ea109efd9387f9b55d2845c745b3a93658af5db9ba8e7301c86a5R393

**Comment by ghenry** [comment]
Yep, that's what prompted me to re-open as it jogged my memory. Great, will
have a play! Thanks!
