### ISSUE TITLE
Connect via SIP without websocket

### ISSUE THREAD

**Issue by joaquin03** [flutter-webrtc/dart-sip-ua#126]
Hi! 
I am new to this. My client has intercoms and wants an app with videocall to them. 
They told me the intercoms have their own server and the only thing I need to do is to connect with the IP to the sip port. And that´s all they provided me, the Ips and SIP port.

Is there a way this is achievable without the websocket?

Thanks!

**Comment by ghenry** [comment]
Sorry, this is SIP over websocket only.

**Comment by joaquin03** [comment]
Thanks!

**Comment by aososam** [comment]
@joaquin03 Did you find any other option?

**Comment by joaquin03** [comment]
We setup an Asterisk Server and integrate everything on that
