### ISSUE TITLE
Member RTCIceServer.urls is required and must be an instance of (DOMString or sequence)

### ISSUE THREAD

**Issue by gittycoder02** [flutter-webrtc/dart-sip-ua#128]
**Describe the bug**
Encounter Error: Unhandled Promise Rejection: TypeError: Member RTCIceServer.urls is required and must be an instance of (DOMString or sequence)

**To Reproduce**
Steps to reproduce the behavior:Member RTCIceServer.urls is required and must be an instance of (DOMString or sequence)
1. Go to Safari Browser
2. Launch Web Application
3. After registration, click on call button

**Comment by arijitnaskar** [comment]
I am getting the same issue in Safari (version 14.0.3) Mac OS Big Sur. Any solution Please.
My Code is below:
```
var configuration = 
      {
        "iceServers": [
          {"url": "stun:stun2.1.google.com:19302"},
         // {"url": "http://stun.l.google.com:19302/"}
        ]
      };
      var con = new RTCPeerConnection(configuration);
```

**Comment by yangmingli08** [comment]
> I am getting the same issue in Safari (version 14.0.3) Mac OS Big Sur. Any solution Please. My Code is below:
> 
> ```
> var configuration = 
>       {
>         "iceServers": [
>           {"url": "stun:stun2.1.google.com:19302"},
>          // {"url": "http://stun.l.google.com:19302/"}
>         ]
>       };
>       var con = new RTCPeerConnection(configuration);
> ```
change your code to
```
var configuration = 
      {
        "iceServers": [
		{
		"urls":  ["stun:stun2.1.google.com:19302"]
		}
	]
      };
var con = new RTCPeerConnection(configuration);
```
