### ISSUE TITLE
Excuting call when app is in background or terminated.

### ISSUE THREAD

**Issue by vinhcuong** [flutter-webrtc/dart-sip-ua#131]
Firstly, i want to thank all of volunteers who are building this package. This saved my life when i had a task building a flutter app excuting Sip call. But i have issues, i want to call when app is in background or terminal. I know issue relating background or terminated app is very hard for crossplatform. I think i can use firebase message for Android and PushKit for iOS. But i have trouble when i try to integrate to my app. The problem is dart sip ua package receive phone call and navigator to call screen. I want to push notification before this process. Please help me. Thank you so much. Please sympathize with me becasue my english not good.

**Comment by cloudwebrtc** [comment]
I think you need to use RFC8599 to do the offline call push.
https://github.com/flutter-webrtc/dart-sip-ua/issues/89

**Comment by ghenry** [comment]
Yes, this is the way.

**Comment by vinhcuong** [comment]
In my case, I can't do any change in SIP server, I just change code in Flutter app. I'm trying use flutter_callkeep to solve this problem. So, how i can get call ID. I can get session ID and call ID is a substring of session ID but lenght of call ID is not identic. Thank you.

**Comment by RaviGaruda** [comment]
hey @vinhcuong have you found any way to do this?

**Comment by alaayousf** [comment]
Has anyone solved this problem please? I've been looking for a solution for a while
  I want to receive calls when it is locked or in the background, I use the [sip ua dart](https://pub.dev/packages/sip_ua/changelog)

**Comment by ahmedradwan18** [comment]
has anyone found a solution? I use FCM to wake up the app but I cant listen to sip listener at top level method.

**Comment by alaayousf** [comment]
You can enter an meeting with me, I speak Arabic

**Comment by ahmedradwan18** [comment]
Can you call me what's app on 01122388139 , I am very grateful

**Comment by alaayousf** [comment]
Give me your email address

**Comment by ahmedradwan18** [comment]
Sure, here it is. ***@***.***

**Comment by alaayousf** [comment]
The email is hidden....Go to my account on github, you will find my email, contact me using it

**Comment by JIJO-cs** [comment]
hi friends did you get a solution for this?

**Comment by ghenry** [comment]
You wake it up with a push notification
.

**Comment by ghenry** [comment]
https://blog.opensips.org/2020/06/03/sip-push-notification-with-opensips-3-1-lts-rfc-8599-supportpart-ii/

**Comment by piyushkb** [comment]
> [alaayousf](/alaayousf)

hi do you have any solution

**Comment by piyushkb** [comment]
> hey @vinhcuong have you found any way to do this?

any solutioun?

**Comment by md-riaz** [comment]
wake up part didn't share anyone 😒

**Comment by harryandroiddev** [comment]
same issue

**Comment by md-riaz** [comment]
Callkeep does not work with latest Android version and requires an activity which means app need to be always running in background making the whole push notification call process useless 🪴
