### ISSUE TITLE
Android video support h264 codec

### ISSUE THREAD

**Issue by joaquin03** [flutter-webrtc/dart-sip-ua#134]
Hi! I am currently videocalling an intercom which sends video in h.264 codec, in the Chrome installation it works fine, but in the Android installation, I make the same call and there is no video. 

Any ideas why this is happening?

Thanks!

**Comment by cloudwebrtc** [comment]
The video encoding capability of android depends on the GooglWebRTC native SDK, dart-sip-ua only uses the flutter-webrtc interface package, so the encoding capability cannot be operated.

**Comment by morfair** [comment]
How to update GooglWebRTC native SDK for Flutter project?
