### ISSUE TITLE
send dtmf bind on key

### ISSUE THREAD

**Issue by prozaklob** [flutter-webrtc/dart-sip-ua#142]
Hi! Is it possible to somehow implement sending a DTMF signal by pressing a simple button during a call?

To avoid creating another branch:
is it possible to set a sound signal during a call?

Do not throw in tomatoes. I'm still learning. I will learn - I will help others. :)

thx

**Comment by ghenry** [comment]
Only SIP INFO is support. I'm working with @cloudwebrtc for https://github.com/flutter-webrtc/dart-sip-ua/issues/105 for "normal" DTMF :-)

**Comment by prozaklob** [comment]
> Only SIP INFO is supported. I'm working with @cloudwebrtc for #105 for "normal" DTMF :-)

oh. nice
and what about sound? )

**Comment by ghenry** [comment]
Read the issue, you'll see.

**Comment by prozaklob** [comment]
both questions remained open to me.
In the issues, I did not find an answer by sound.
DTMF suits me both as rfc2833 and as sip info.
You can open a little information on how to send rfc or sip info?
thx

**Comment by ghenry** [comment]
See the example app. It was updated to show all this.
