### ISSUE TITLE
issue with phone call

### ISSUE THREAD

**Issue by ShalevCohen2112** [flutter-webrtc/dart-sip-ua#146]
After receiving the phone call and answer the call been ended with error : call failed with cause: Code: [488], Cause: Bad Media Description, Reason: Not Acceptable Here. flutter web,android

**Comment by cloudwebrtc** [comment]
This problem is related to SDP media negotiation, please check whether your media server has ice, RTCP-fb,  SAVPF enabled

**Comment by ShalevCohen2112** [comment]
thanx...
now i reciveing 
emit "peerconnection:setremotedescriptionfailed" [error:InvalidStateError: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: Called in wrong state: stable]
