### ISSUE TITLE
Camera can not release [Android]

### ISSUE THREAD

**Issue by ZZXUN233** [flutter-webrtc/dart-sip-ua#150]
https://github.com/flutter-webrtc/dart-sip-ua/blob/10575278aa5bb660038bfa7fd51b91bee241e634/lib/src/rtc_session.dart#L1469

**Describe the bug**
when the call is ended, android device can not release the camera, logs keep showing 
![image](https://user-images.githubusercontent.com/33314081/98062534-34325a00-1e89-11eb-8c02-10cf39802b96.png)

**Expected behavior**
when call is ended, the camera should be release. 

**System Infomation()**
Flutter SDK Version: Flutter (Channel dev, 1.23.0-18.0.pre
Target OS and Version: Android SDK version 30.0.2
Host OS and Version:  Microsoft Windows [Version 10.0.19041.572]

Thanks for your good job!

**Comment by ZZXUN233** [comment]
The flutter webrtc example works fine, camera can be released as normal.
https://github.com/flutter-webrtc/flutter-webrtc/blob/e177408ff02bac6c99bda1da592fb1ef31562ecf/example/lib/src/get_user_media_sample.dart#L77

**Comment by MahmoudMamdoouh** [comment]
> The flutter webrtc example works fine, camera can be released as normal. https://github.com/flutter-webrtc/flutter-webrtc/blob/e177408ff02bac6c99bda1da592fb1ef31562ecf/example/lib/src/get_user_media_sample.dart#L77

i have the same problem it happens random
