### ISSUE TITLE
Unable to make a call - [488] Not Acceptable Here

### ISSUE THREAD

**Issue by mrkobby** [flutter-webrtc/dart-sip-ua#152]
Hi there, 
I recently added the WebRTC support configurations to my asterisk server following this [tutorial](https://wiki.asterisk.org/wiki/display/AST/Configuring+Asterisk+for+WebRTC+Clients).  I'm able to successfully register an account but when making a call, it disconnects after 4 secs. Not sure where the problem is, but here are the logs:

>  I/flutter ( 6828): [2020-11-08 20:21:29.657] Level.debug rtc_session.dart:2215 ::: receiveInviteResponse()
I/flutter ( 6828): [2020-11-08 20:21:29.670] Level.debug websocket_interface.dart:164 ::: Received WebSocket message
I/flutter ( 6828): [2020-11-08 20:21:29.677] Level.debug transport.dart:314 ::: received text message:
I/flutter ( 6828): 
I/flutter ( 6828): SIP/2.0 488 Not Acceptable Here
I/flutter ( 6828): Via: SIP/2.0/WSS ri49964770ws.invalid;rport=25927;received=154.160.30.221;branch=z9hG4bK3196774880000000
I/flutter ( 6828): Call-ID: 08v07i4mcclzclhciae3
I/flutter ( 6828): From: "Tester One" <sip:02090xxxxxx@3.130.xxx.xxx>;tag=snyrikchig
I/flutter ( 6828): To: <sip:500@3.130.xxx.xxx>;tag=0466db44-87a7-4ad7-ba49-6dff7fa39a94
I/flutter ( 6828): CSeq: 4932 INVITE
I/flutter ( 6828): Server: Asterisk PBX 17.3.0
I/flutter ( 6828): Content-Length:  0
I/flutter ( 6828): 
I/flutter ( 6828): [2020-11-08 20:21:29.722] Level.debug rtc_session.dart:2215 ::: receiveInviteResponse()
I/flutter ( 6828): [2020-11-08 20:21:29.727] Level.debug rtc_session.dart:2868 ::: session failed
I/flutter ( 6828): [2020-11-08 20:21:29.733] Level.debug rtc_session.dart:2871 ::: emit "_failed"
I/flutter ( 6828): [2020-11-08 20:21:29.738] Level.debug rtc_session.dart:1450 ::: close()
D/FlutterWebRTCPlugin( 6828): onConnectionChangeCLOSED
I/flutter ( 6828): [2020-11-08 20:21:29.744] Level.debug rtc_session.dart:2882 ::: emit "failed"
I/org.webrtc.Logging( 6828): NetworkMonitor: Stop monitoring with native observer 492335202624
I/org.webrtc.Logging( 6828): NetworkMonitorAutoDetect: Unregister network callback
D/ConnectivityManager( 6828): unregisterNetworkCallback; CallingUid : 10060, CallingPid : 6828
I/flutter ( 6828): [2020-11-08 20:21:29.750] Level.debug sip_ua_helper.dart:200 ::: call failed with cause: Code: [488], Cause: Incompatible SDP, Reason: Not Acceptable Here
I/flutter ( 6828): [2020-11-08 20:21:29.757] Level.debug invite_client.dart:91 ::: Timer D expired for transaction z9hG4bK3196774880000000
D/RTCAudioManager( 6828): stop`

Any help will be greatly appreciated. Thanks alot and great work!

**Comment by cloudwebrtc** [comment]
@mrkobby You need to check from Asterisk why the SDP sent by dart-sip-ua is rejected, usually asterisk about webrtc related configuration issues, such as RTCP-FB, ice, or codecs.

**Comment by mrkobby** [comment]
Thanks for the reply. I'll check my pjsip configuration again.

**Comment by cloudwebrtc** [comment]
Here is a working docker for asterisk, this is the configuration I passed the test, you can refer to the config file, I hope it can help you.
https://github.com/flutter-webrtc/dockers/tree/main/asterisk

**Comment by mrkobby** [comment]
Nice one! This should work. Thanks

**Comment by mrkobby** [comment]
Hello @cloudwebrtc and @ghenry, I've been following your work. Great job! 
With your help I've managed to get the app working! 
It works perfectly on Android but when I try to make a **cross-platfom call (from an iPhone to an Android device)**, there's no audio. I have added the microphone permission to my **Info.plist** but the audio isn't working. 
Any help will be appreciated. Thanks

**Comment by ghenry** [comment]
You'll need to debug the SIP.

**Comment by mrkobby** [comment]
Thanks for the reply.
What's the best way to debug please?
I using an asterisk server. I used Wireshark to monitor the packets sent and received. My audio port is opened but no audio is sent to the server.

**Comment by ghenry** [comment]
Do SIP trace debug to confirm it's not a NAT thing etc. Nothing to do with
dart-sip-ua until you confirm that.
-- 
Kind Regards,

Gavin Henry.
Managing Director.

T +44 (0) 330 44 50 000
D +44 (0) 330 44 55 007
M +44 (0) 7930 323266
F +44 (0) 1224 824887
E ghenry@surevoip.co.uk

Open Telecoms for Business (tm).

http://www.surevoip.co.uk

Suretec Systems is a limited company registered in Scotland. Registered
number: SC258005. Registered office: 24 Cormack Park, Rothienorman,
Inverurie, Aberdeenshire, AB51 8GL.

Subject to disclaimer at http://www.suretecgroup.com/disclaimer.html

OpenPGP (GPG/PGP) Public Key: 0x8CFBA8E6 - Import from
hkp://pool.subkeys.pgp.net
or http://www.suretecgroup.com/0x8CFBA8E6.gpg

**Comment by mrkobby** [comment]
Hello, please I've debugged the SIP. 
Everything looks good on the Asterisk server. 
I call an {extension} from dart-sip-ua to another using a zipper app. The call was successful and audio was clear.
But _dart-sip-ua(Android)_ to _dart-sip-ua(iOS)_ has no audio. 
What can I do next please? Are any special configurations for iOS please?
Thanks alot.

**Comment by ghenry** [comment]
You'll need to debug the SIP and SDP on that call scenario. It will be
unrelated to sip-ua.

Thanks.

**Comment by cycloss** [comment]
Try adding `webrtc=yes` to your endpoint in Asterisk's pjsip config.
