### ISSUE TITLE
Feature Request: Expose DTMF options from RTCSession to Call.sendDTMF

### ISSUE THREAD

**Issue by Gleydar** [flutter-webrtc/dart-sip-ua#153]
Due to a specific implementation of a server, I want to send DTMF tones of a specified length. Currently, this seems impossible to me using the Call instance I work with.

The Instance of RTCSession used internally in the Call however, already has a parameter to specify these durations.

It would be very useful for me if this optional parameter was made aviable in the call itself.

**EDIT:**
I have proposed a change that would fix this request in #154

**Comment by cloudwebrtc** [comment]
merged
