### ISSUE TITLE
Issue create the call !!!

### ISSUE THREAD

**Issue by ShalevCohen2112** [flutter-webrtc/dart-sip-ua#156]
after entering the progress state i receive this exception and i canot war the other side talking.

Unhandled Exception: Unable to RTCPeerConnection::setRemoteDescription: peerConnectionSetRemoteDescription(): WEBRTC_SET_REMOTE_DESCRIPTION_ERROR: Failed to set remote answer sdp: Called in wrong state: stable
    #0      RTCPeerConnectionNative.setRemoteDescription (package:flutter_webrtc/src/native/rtc_peerconnection_impl.dart:329:7)
    <asynchronous suspension>
    #1      RTCSession._receiveInviteResponse (package:sip_ua/src/rtc_session.dart:2293:21)
    #2      RTCSession._sendInitialRequest.<anonymous closure> (package:sip_ua/src/rtc_session.dart:2137:7)
    #3      EventManager.emit.<anonymous closure> (package:sip_ua/src/event_manager/event_manager.dart:108:17)
    #4      List.forEach (dart:core-patch/growable_array.dart:313:8)
    #5      EventManager.emit (package:sip_ua/src/event_manager/event_manager.dart:105:12)
    #6      RequestSender._receiveResponse (package:sip_ua/src/request_sender.dart:157:22)
    #7      RequestSender.send.<anonymous closure> (package:sip_ua/src/request_sender.dart:59:7)
    #8      EventManager.emit.<anonymous closure> (package:sip_ua/src/event_manager/event_manager.dart:108:17)
    #9      List.forEach (dart:core-patch/growable_array.dart:313:8)
    #10     EventManager.emit (package:sip_ua/src/event_manager/event_manager.dart:105:12)
    #11     InviteClientTransaction.receiveResponse (package:sip_ua/src/transactions/invite_client.dart:152:26)
    #12     UA.onTransportData (package:sip_ua/src/ua.dart:860:25)
    #13     Transport._onData (package:sip_ua/src/transport.dart:317:11)
    #14     WebSocketInterface._onMessage (package:sip_ua/src/transports/websocket_interface.dart:167:15)
    #15     WebSocketInterface.connect.<anonymous closure> (package:sip_ua/src/transports/websocket_interface.dart:87:9)
    #16     WebSocketImpl.connect.<anonymous closure> (package:sip_ua/src/transports/websocket_dart_impl.dart:37:20)
    #17     _rootRunUnary (dart:async/zone.dart:1198:47)
    #18     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
    #19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
    #20     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
    #21     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
    #22     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
    #23     _StreamController._add (dart:async/stream_controller.dart:682:7)
    #24     _StreamController.add (dart:async/stream_controller.dart:624:5)
    #25     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1145:21)
    #26     _rootRunUnary (dart:async/zone.dart:1198:47)
    #27     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
    #28     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
    #29     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
    #30     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
    #31     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
    #32     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
    #33     _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:338:23)
    #34     _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:232:46)
    #35     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
    #36     _rootRunUnary (dart:async/zone.dart:1198:47)
    #37     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
    #38     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
    #39     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
    #40     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
    #41     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
    #42     _StreamController._add (dart:async/stream_controller.dart:682:7)
    #43     _StreamController.add (dart:async/stream_controller.dart:624:5)
    #44     _Socket._onData (dart:io-patch/socket_patch.dart:1969:41)
    #45     _rootRunUnary (dart:async/zone.dart:1198:47)
    #46     _CustomZone.runUnary (dart

**Comment by eduardothiesen** [comment]
I am also facing this issue. @ShalevCohen2112 did you find a solution?
