### ISSUE TITLE
support of ZRTP encryption

### ISSUE THREAD

**Issue by 2math** [flutter-webrtc/dart-sip-ua#158]
Hi, for start great library!

I can not find anywhere in the code option to set encryption.
I have a client that wants me to integrate a sip protocol with ZRTP encryption.
Is that possible with current package?
Thanks in advance!

**Comment by cloudwebrtc** [comment]
This package is based on flutter-webrtc so it can only support DTLS-SRTP.

**Comment by 2math** [comment]
Thank you!
