### ISSUE TITLE
SIP UA and external bluetooth devices (car / speakers)

### ISSUE THREAD

**Issue by PaulBout1** [flutter-webrtc/dart-sip-ua#159]
Hi there !
First I'd like to **THANK** you for the awesome library you provide. 
The only issue I met is : The app does not send sound through the bluetooth if an external device is paired to the smartphone.

The `MediaStreamTrack` received from SIP UA allows me to enable speakers or mute mic. what about bluetooth ?

**To Reproduce**
1. Pair an android device to a car or a nomad speaker
2. make a call (register + call)

**Expected behavior**
Sound should be played from the nomad or car speaker not the smartphone anymore

**System Infomation()**
Flutter SDK Version: 1.22.4
Target OS and Version: Android v9
Host OS and Version: macOS 11.0.1

**Comment by PaulBout1** [comment]
Actually it works. 
I had to add permission in android.manifest file and use a BT external devices equipped with a mic and a speaker. 

Cheers

Again GREAT JOB to the WebRTC TEAM

**Comment by PaulBout1** [comment]
Actually it works. 
I had to add permission in android.manifest file and use a BT external devices equipped with a mic and a speaker. 

Cheers

Again GREAT JOB to the WebRTC TEAM

**Comment by ghenry** [comment]
I'm pretty sure that perm is in the example app already?

**Comment by ghenry** [comment]
Actually the project tool doesn't add that. We'll need to update the docs. Thanks for the report.
