### ISSUE TITLE
Having issues with registering on Freeswitch

### ISSUE THREAD

**Issue by eldarj** [flutter-webrtc/dart-sip-ua#160]
Hello there, hopefully someone could help out a bit with this

I'm trying out the dart sip ua client demo, with a mostly default configured Freeswitch, running everything in my lan.

The issue is, that I'm getting 200 on registering to an extension e.g. sip:1000@my.fs.in.lan.ip, but I can't make any calls.

If I try and make a call from another client to the dart ua demo client, I'm just getting "Answered" which is rather weird. Also when I try to create a call from dart demo client to another client, I'm getting the next error "Level.error sip_ua_helper.dart:76 ::: Not connected, you will need to register"

Besides that, on my Freeswitch, I can see that I get registered with the demo app, and at the right extension, but with this weird contact e.g.
```
sofia/internal/sip:8y275sq0@8863bs810j58.invalid;fs_nat=yes;fs_path=sip%3A8y275sq0%40192.168.1.3%3A59518

```

Is this weird? Am I missing something?

**Comment by ghenry** [comment]
Hi,

I’m presuming you’ve correctly setup websockets etc as you’re registered.
What do the invites look like?

Thanks.
-- 
Kind Regards,

Gavin Henry.
Managing Director.

T +44 (0) 330 44 50 000
D +44 (0) 330 44 55 007
M +44 (0) 7930 323266
F +44 (0) 1224 824887
E ghenry@suretec.co.uk

Open Source. Open Solutions(tm).

http://www.suretecsystems.com/

Suretec Systems is a limited company registered in Scotland. Registered
number: SC258005. Registered office: 24 Cormack Park, Rothienorman,
Inverurie, Aberdeenshire, AB51 8GL.

Subject to disclaimer at http://www.suretecgroup.com/disclaimer.html

**Comment by eldarj** [comment]
Hi;

Thank you for your reply. I actually figured it the issue was on flutter side with permissions, but still having the issue with the **Contact** header.

Thanks

**Comment by ghenry** [comment]
That's good! What's wrong with the Contact header?

**Comment by eldarj** [comment]
Thanks ghenry

I guessed something is off with it, but it's fine though?

Also after testing out - I'm able to call from the dart demo to other clients, but can't receive calls on dart demo.

Any tips what should I look into, what could I be missing?

**Comment by ghenry** [comment]
Is the FreeSWITCH sending webrtc SDP data? If you're registering directly
it will know it's webrtc. Are you using wss?

**Comment by ZZXUN233** [comment]
I find that there is no "transport=ws;" in your Contact header,  just comment the code in 
~~~   
   // Custom Contact URI params for REGISTER and un-REGISTER.
    //setExtraContactUriParams(
       // ua.configuration.register_extra_contact_uri_params);
~~~
[here](https://github.com/flutter-webrtc/dart-sip-ua/blob/c55c62aef0a817c368d630fa21a2a8bb12d435aa/lib/src/registrator.dart#L63)
can fix it.  and you may ask @ghenry why to add the lines, the git log is " extraContactUriParams now working and tested against OpenSIPS 3.1 that has RFC8599 support. Refs #89 - https://github.com/cloudwebrtc/dart-sip-ua/issues/89
" with this commit "SHA-1: f3394d9d950201ddb8ca8cfa156f2c2a18930547"

**Comment by ghenry** [comment]
Hi @ZZXUN233 

That setting is used to do this where you add params to the Contact header:

https://tools.ietf.org/html/rfc8599#page-12

```
     REGISTER sip:alice@example.com SIP/2.0
     Via: SIP/2.0/TCP alicemobile.example.com:5060;branch=z9hG4bKnashds7
     Max-Forwards: 70
     To: Alice <sip:alice@example.com>
     From: Alice <sip:alice@example.com>;tag=456248
     Call-ID: 843817637684230@998sdasdh09
     CSeq: 1826 REGISTER
     Contact: <sip:alice@alicemobile.example.com;
       pn-provider=acme;
       pn-param=acme-param;
       pn-prid=ZTY4ZDJlMzODE1NmUgKi0K>;
       +sip.pnsreg
     Expires: 7200
     Content-Length: 0
```

e.g.

```
    UaSettings settings = UaSettings();

....

    if (GetPlatform.isAndroid || GetPlatform.isWeb) {
      settings.registerParams.extraContactUriParams = <String, String>{
        'pn-provider': 'fcm',
        'pn-param': FCM_PROJECT_ID,
        'pn-prid': _fcmToken
      };
    }
```

Are you saying without anything set in `settings.registerParams.extraContactUriParams` then `transport=ws` doesn't get added? If so, why haven't you reported this?

Thanks.
