### ISSUE TITLE
 Program type already present: org.webrtc.AndroidVideoDecoder$1

### ISSUE THREAD

**Issue by deep1931** [flutter-webrtc/dart-sip-ua#165]
While compiling I am getting ` Program type already present: org.webrtc.AndroidVideoDecoder$1` error. Not able to diagnose the clash.

**Comment by cloudwebrtc** [comment]
Is another webrtc project used in your project?

**Comment by deep1931** [comment]
no, I just added this plugin and try to run the app and received this error. I have tried to diagnose the existing plugins so that I can find defaulter class, but not find other packages

**Comment by cloudwebrtc** [comment]
If you are adding the flutter_webrtc plug-in to your project, please confirm that the permission tag has been added, and if you want the community to help you solve the problem, you usually need more detailed log context.

**Comment by deep1931** [comment]
Here is the log, hope it helps. This issue came with both sip_ua and flutter_webrtc plugin.


`D8: Program type already present: org.webrtc.AndroidVideoDecoder$DecodedTextureMetadata

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: org.webrtc.AndroidVideoDecoder$DecodedTextureMetadata

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 11s
Exception: Gradle task assembleDebug failed with exit code 1`
