### ISSUE TITLE
Is there any possibility to disable ICE?

### ISSUE THREAD

**Issue by Dhawansumit** [flutter-webrtc/dart-sip-ua#167]
There is delay of 3 seconds (fixed) while searching and Connecting to ice candidates as mentioned in rtc_session.dart 

**_connection.onIceCandidate = (RTCIceCandidate candidate) {
      if (candidate != null) {
        emit(EventIceCandidate(candidate, ready));
        if (!finished) {
          finished = true;
          /**
           *  Just wait for 3 seconds. In the case of multiple network connections,
           *  the RTCIceGatheringStateComplete event needs to wait for 10 ~ 30 seconds.
           *  Because trickle ICE is not defined in the sip protocol, the delay of
           * initiating a call to answer the call waiting will be unacceptable.
           */
          setTimeout(() => ready(), 3000);
        }
      }
    };**

Question 1 . :- is there any possibility to disable ICE from the client side?

**Comment by ghenry** [comment]
Yep, you can disable this by doing (make sure you always search closed GH issues too :-) ):

```
    // https://github.com/flutter-webrtc/dart-sip-ua/issues/136#issuecomment-732970413
    // Not needed.
    settings.iceServers = [];
```
