### ISSUE TITLE
Incoming call type

### ISSUE THREAD

**Issue by magnocasmor** [flutter-webrtc/dart-sip-ua#171]
Hello, I would like to know if it is possible to identify the type of the incoming call, if is audio call or video call. And, if it is possible to identify the type, can I show the local video stream while is ringing?

Thanks!

**Comment by cloudwebrtc** [comment]
You need to parse the offer SDP of the incoming call to see if it contains a video media-line.

**Comment by magnocasmor** [comment]
Unfortunately the `session` variable is private in the class `Call` and `request`is private in `RTCSession`

**Comment by cloudwebrtc** [comment]
@magnocasmor, please try this commit https://github.com/flutter-webrtc/dart-sip-ua/commit/a1c25ade11f8175135746d1230f270bf9ecf6cb7

**Comment by magnocasmor** [comment]
It's work. But I'm more interested in showing local camera stream while receive incoming call.

When the local makes call, the method `callStateChanged` emits the following sequence of `CallStateEnum` while ringing:

![Captura de Tela 2021-02-07 às 16 30 10](https://user-images.githubusercontent.com/45497497/107157231-bf782b80-6961-11eb-960b-1381588b826f.png)

Because this, the local can show user's camera stream before the remote answer/rejected

But, when the local receives incoming call, the method `callStateChanged` emits the following sequence of `CallStateEnum` while ringing:

![Captura de Tela 2021-02-07 às 16 33 28](https://user-images.githubusercontent.com/45497497/107157312-34e3fc00-6962-11eb-85c8-34124c4bb9e6.png)

So, there are no `CallStateEnum.STREAM` that local can show user's camera stream if is video call or show a screen without the camera stream if is audio call like WhatsApp, for example.

I submitted a [PR](https://github.com/flutter-webrtc/dart-sip-ua/pull/174) with changes to satisfy this. Can you check if this is okay? Thanks!

**Comment by cloudwebrtc** [comment]
hey @magnocasmor, I don’t think you need to do this PR, just add `mediaStream` to the options in the answer.

```dart
@override
  void callStateChanged(Call call, CallState callState) {
    if (callState.state == CallStateEnum.CALL_INITIATION && callState.direction == 'INCOMING') {
          var mediaStream = await navigator.mediaDevices.getUserMedia({
              'audio': call.remote_has_audio, 
              'video': call.remote_has_video,
              );
          
          // Display the video stream.
          
          ....

         // Use the created `mediaStream` to answer the call
         call.answer(Map<String,dynamic>{'mediaStream', mediaStream});
    }
  }
```

**Comment by magnocasmor** [comment]
I tested the commit a1c25ad but it's works only for incoming call. On outgoing call the getters `call.remote_has_audio` and `call.remote_has_video` always returns `false`.

I noticed that these getters call internally `_session.request.parseSDP()` but on outgoing call the  SDP is a empty array.

I maked calls with `voiceonly` option set to `false`.
