### ISSUE TITLE
Receiver side call request not coming with FreeSwitch server

### ISSUE THREAD

**Issue by mayurviras** [flutter-webrtc/dart-sip-ua#181]
Hello all,
          I'm developing calling app using our own freeswitch sever. i have done app side configuration like added wss url and sip url. currently SIP connection working fine. but when i send call request to server that time request coming in server but not coming in receiver end and after 30 second call is going in voice mail. please help me in this issue.

Note:- i have tested calls with other open source SIP server which is running on overSIP and call is working fine with this server.

**Comment by cloudwebrtc** [comment]
I think you need to check the FreeSWitch settings, it seems to be the bLeg side call issue of B2BUA.
