### ISSUE TITLE
No call audio on real device but call audio is fine in emulator...

### ISSUE THREAD

**Issue by chuckwhisler** [flutter-webrtc/dart-sip-ua#182]
When i am calling from emulator the call have audio but when i am calling from the real device there is no audio tried changing and adding all the audio permissions even tried adding CALL_PHONE permission but no success. Using example dart sip ua project as a base but both not working....

**Comment by viniciusoliverrs** [comment]
Hi, how did you resolve this issue?

**Comment by chuckwhisler** [comment]
Added coturn server for ice candidates.
