### ISSUE TITLE
I want to open application from background when I have received invite message.

### ISSUE THREAD

**Issue by 97loser** [flutter-webrtc/dart-sip-ua#183]
Hello,
  I'm very excited to use this library and resolved my real world problems.
  but I'm stuck when my application is in background and someone want to call me.
  I have received invite message but unable to open mobile application.
  I don't want to integrate notifications because I want to build apps like WhatsApp.
  so please help me.

**Comment by sashker** [comment]
I don' this there are many alternatives rather than using PUSH messages and Google FCM

**Comment by cloudwebrtc** [comment]
@97loser Take android as an example, if you do receive an invite in the background, just add the following code to the native part to wake up the app UI.
https://github.com/flutter-webrtc/callkeep/blob/master/android/src/main/java/io/wazo/callkeep/CallKeepModule.java#L545
If you are on iOS, you must use PushKit + CallKit in callkeep to wake up your app, and you must pass [RFC8599](https://tools.ietf.org/html/rfc8599) to complete the standard process.

This is a complicated process that must work together through the server, dart-sip-ua and the client's native push function

**Comment by cloudwebrtc** [comment]
I know this is difficult. For other IP PBX, you must upgrade the server accordingly.
But if you want to try to run the complete RFC8599 function, you can use my other [b2bua open-source project](https://github.com/cloudwebrtc/go-sip-ua) to test, this project can use FCM+APNS and dart-sip-ua to run together, and realize the background state, or the app is killed The process of being awakened to answer the call.

**Comment by anmolstuteja** [comment]
Facing similar issue, if someone can help with this problem where I want to receive a call when the app is in background or is terminated.
