### ISSUE TITLE
Feature Request: Expose sendInfo from RTCSession to Call.sendInfo

### ISSUE THREAD

**Issue by makstheimba** [flutter-webrtc/dart-sip-ua#185]
I want to send some custom info using sip_ua library but it's currently impossible cause Call doesn't expose `sendInfo` that is defined on RTCSession.

I think it could implemented as simple as exposing `sendInfo` method on Call and proxying all parameters to `sendInfo` of RTCSession

**Comment by cloudwebrtc** [comment]
I am very busy lately, so I cannot submit the patch in time. If you want, I would be happy to accept a PR and review it for you.
I think you can implement the sendInfo and onInfoRecevied listening events in the Call at the same time, which allows you to send and receive any events other than DTMF Info during the Call Session.

**Comment by makstheimba** [comment]
Thanks, I'm planning to create pr on weekends
