### ISSUE TITLE
Is it possible to use this package with a sip URI an a turn server instead of web socket?

### ISSUE THREAD

**Issue by elianmortega** [flutter-webrtc/dart-sip-ua#193]
I'm working as a freelancer developing an app that makes a call working like a PBX, my client provided me with sip URI and a turn server is it possible to make the implementation of the system using this package.

When I tried I get an error that my turn server is not compatible with the web socket URI which is completely logical, and I wanted to know if there is a workaround, or should I just use flutter_webrtc?

**Comment by cloudwebrtc** [comment]
Can you provide a detailed error log?

**Comment by elian-ortega** [comment]
I made my initial question wrong.

I'm trying to create an app that uses the package to make a call using my client sip server.

**1st Scenario**
When creating the UaSetting to start the connection from the SipUAHelper if i put the 
`..webSocketSettings.allowBadCertificate = true` i get this error

![image](https://user-images.githubusercontent.com/54898038/113922668-ccb86780-97a4-11eb-9f92-e434f72b0c5e.png)

If i put the variable to false I don't get that error but i get this:
![image](https://user-images.githubusercontent.com/54898038/113922779-f3769e00-97a4-11eb-83be-e6a4f14c91de.png)

**Comment by cloudwebrtc** [comment]
Looks like a bug in the grammar parser xD.

**Comment by cloudwebrtc** [comment]
@elian-ortega Please try this commit https://github.com/flutter-webrtc/dart-sip-ua/commit/e6810ec6d49d82c9210fc751af00888756e1310c

**Comment by elian-ortega** [comment]
Thanks @cloudwebrtc I'll try it out and let you know

**Comment by siddharthJadhav** [comment]
I am also facing the same issue. Did anyone know how can solve this issue?
