### ISSUE TITLE
No audio in background, error messages related to "aurioc" (iOS)

### ISSUE THREAD

**Issue by Dhawansumit** [flutter-webrtc/dart-sip-ua#197]
I'm using auto-answering feature in my app. When app is in foreground , everything is working fine .
But when app in background , not able to listen anything , I can see in console , call is getting connected (speaker is enabled) .
and getting this message after that:

**[aurioc] AURemoteIO.cpp:1936:Run: AURemoteIO@0x10603d840: IOThread exiting with error 0x10004006
[aurioc] AURemoteIO.cpp:1598:Start: AUIOClient_StartIO failed (561145187)**

Please help me out . I need to run my app in foreground as well as background.

**Comment by cloudwebrtc** [comment]
![image](https://user-images.githubusercontent.com/17733746/114020541-4aae6880-98a2-11eb-904a-588799576729.png)

**Comment by Dhawansumit** [comment]
Issue Not solved
I have already enabled Voice Over IP . 
![Screenshot 2020-12-21 at 2 37 13 PM](https://user-images.githubusercontent.com/58001415/114023280-5133e480-9890-11eb-9135-9b4b81721e6b.png)
![Screenshot 2021-04-08 at 5 33 00 PM](https://user-images.githubusercontent.com/58001415/114023429-7d4f6580-9890-11eb-95ea-1fefeec62ba5.png)

When app is in foreground , it is working fine. But in background getting error message (as mentioned in first comment)

Explaining the issue again :
I'm answering the call when we get callStateChanged callback 
So when app is in foreground , call is connected and we are able to hear 
But When app is in background , Call is connected and we are not able to hear (getting "aurioc" error in console)

one more scenario :
if app is in foreground , call came and connected , I minimise the app, still the call is connected and able to hear 
Now app is in background and I'm still hearing  , Now one more call comes and hanged up previous one and auto answer that call from code , now I can hear from latest call. 
So do we need a active call when we are in background ? (we don't need this)

Please help me out .
