### ISSUE TITLE
Make it Flutter 2.0 supportive.

### ISSUE THREAD

**Issue by 97loser** [flutter-webrtc/dart-sip-ua#202]
Hello Dev,
  I'm very happy to use your open pub. Here is some problem due to Flutter 2.0. Please update it.
  
  Thank you

**Comment by cloudwebrtc** [comment]
This is a major revision, and I need to have time to do it in June.

**Comment by ghenry** [comment]
I have it working. What's the issue?

**Comment by cloudwebrtc** [comment]
I think it is a null safety migration of the code.

**Comment by ghenry** [comment]
That's different then and the issue needs renamed.

**Comment by sosaucily** [comment]
For me, master branch works well with Flutter 2, but I haven't fully enabled null-safety yet.

**Comment by ghenry** [comment]
Was just looking at this as I'm migrating my own code. Anyone started?

https://dart.dev/null-safety/migration-guide#migration-tool

Thanks.

**Comment by gregorysaml** [comment]
Hello,
I tried migrating the code to nullsafety, for the most part all went well expect one package that is grammar_parser.
The problem is that its generated code and the migration tool seems to just ignore it, Is there any way to get around this?

Thanks

**Comment by ifightcode** [comment]
I'm also waiting for an update. Flutter WebRTC got the required updates, but it's still pending.

**Comment by 97loser** [comment]
...
