### ISSUE TITLE
Error Failed to set remote offer sdp: Called with SDP without DTLS fingerprint.

### ISSUE THREAD

**Issue by RobotMaths** [flutter-webrtc/dart-sip-ua#207]
Hi, I'm using dart_sip package to create an app that receive call from intercom. Intercoms have asterisks and pjsip on Raspberry pi3. When I tried to answer the call (call.answer(helper.buildOption())), I have this error : 

`flutter: [2021-05-31 17:46:47.999] Level.debug sip_ua_helper.dart:203 ::: call failed with cause: Code: [488], Cause: WebRTC Error, Reason: SetRemoteDescription(offer) failed
emit "peerconnection:setremotedescriptionfailed" [error:Unable to RTCPeerConnection::setRemoteDescription: Error Failed to set remote offer sdp: Called with SDP without DTLS fingerprint.]
`

The app crash. My online asterisk (v13) support webrtc ... I don't know what to do, what is this error ?

**Comment by RobotMaths** [comment]
Ok, it was just a server config problem. Have to set in sip.conf : 
dtlsenable=yes
dtlsverify=fingerprint
dtlscertfile=/etc/asterisk/keys/asterisk.pem
dtlscafile=/etc/asterisk/keys/ca.crt. 
But know I have an other problem. When I answer the call, I get an  SIP/2.0 488 Not Acceptable Here. I just allow ulaw, alaw and gsm in the two sides. Why I have this error ? 

![Capture d’écran 2021-06-01 à 12 34 02](https://user-images.githubusercontent.com/85124203/120309599-b37bf500-c2d5-11eb-9ffe-889ca53ade53.png)

**Comment by RobotMaths** [comment]
i forgot to show you my sdp call log that contain savpf : 
![Capture d’écran 2021-06-01 à 16 14 57](https://user-images.githubusercontent.com/85124203/120338543-9e628e80-c2f4-11eb-8b55-451d284b361b.png)

**Comment by cloudwebrtc** [comment]
`setRemoteDescription: Error Failed to set remote offer sdp: Called with SDP without DTLS fingerprint.`
You must enable dtls-srtp on Asterisk, which is mandatory for webrtc

**Comment by RobotMaths** [comment]
Thank you for your reply ! That was I mistake, like you said I just forgot to enable dtls in user.conf. I do not have great knowledge on these protocols ... 
Now, I have a SDP problem, I don't know why because I have sapvf enable and same codec in the two sides .... I post logs of SDP above. Can you help me please ? Do you have an idea why ?

**Comment by RobotMaths** [comment]
Someone can be my savior ? I'm reading some posts but I still really don't see the problem....

**Comment by IuryPiva** [comment]
@RobotMaths running into the same issue here, did you solve yours? Could you point me into any direction?
