### ISSUE TITLE
Upgrade the webrtc version

### ISSUE THREAD

**Issue by zi6xuan** [flutter-webrtc/dart-sip-ua#238]
Is it possible to upgrade the necessary version of webrtc. It was found that the webrtc 0.6.8 version will cause the speaker switch under ios to be invalid during use. So I was wondering if I can upgrade to version 0.6.9 or higher

**Comment by solid-yuriiuvarov** [comment]
@ zi6xuan you can specify this in your project in the pubspec file and the dart sip ua plugin will use your specified version. Note that this will only work with minor versions, so you cannot specify the 0.7.0 version of the webrtc plugin.

Example:
```
dependencies:
 ...
  flutter_webrtc: 0.6.10+hotfix.1
```
