### ISSUE TITLE
Add Null Safety

### ISSUE THREAD

**Issue by amirr-dotcom** [flutter-webrtc/dart-sip-ua#246]
I have tried to run this dependency on latest flutter but because if the null safe issue its not working, which is causing issue to create latest app

If you please add the null safety feature it will be very helpful

**Comment by cloudwebrtc** [comment]
A PR has been created here https://github.com/flutter-webrtc/dart-sip-ua/pull/234, but I have been busy recently, so this PR is in a suspended state, any help is welcome

**Comment by DedicatedDev** [comment]
this is very important problem. I guess there is no upgrade for a month. I've tried to migration myself. but encountered issues which previous developers met already.

**Comment by DedicatedDev** [comment]
https://github.com/flutter-webrtc/dart-sip-ua/issues/219#issuecomment-914377981

**Comment by viplifes** [comment]
I created merge with support null safety https://github.com/flutter-webrtc/dart-sip-ua/pull/247. 
But this work still requires thorough testing.

**Comment by DedicatedDev** [comment]
great. Thank you.

**Comment by jongerenchaos** [comment]
> I created merge with support null safety #247. But this work still requires thorough testing.

For now it does not work. I try your build and register an account to a wss server i get the following errors:
`I/flutter (14513): [2022-02-01 21:00:04.680] Level.error event_manager.dart:110 ::: type 'Null' is not a subtype of type 'bool'
I/flutter (14513): #0      new Challenge.fromMap (package:sip_ua/src/digest_authentication.dart:10:27)
I/flutter (14513): #1      RequestSender._receiveResponse (package:sip_ua/src/request_sender.dart:122:23)
I/flutter (14513): #2      RequestSender.send.<anonymous closure> (package:sip_ua/src/request_sender.dart:57:7)
I/flutter (14513): #3      EventManager.emit.<anonymous closure> (package:sip_ua/src/event_manager/event_manager.dart:108:17)
I/flutter (14513): #4      List.forEach (dart:core-patch/growable_array.dart:433:8)
I/flutter (14513): #5      EventManager.emit (package:sip_ua/src/event_manager/event_manager.dart:105:12)
I/flutter (14513): #6      NonInviteClientTransaction.receiveResponse (package:sip_ua/src/transactions/non_invite_client.dart:96:28)
I/flutter (14513): #7      UA.onTransportData (package:sip_ua/src/ua.dart:882:25)
I/flutter (14513): #8      Transport._onData (package:sip_ua/src/transport.dart:316:11)
I/flutter (14513): #9      WebSocketInterface._onMessage (package:sip_ua/src/transports/websocket_interface.dart:172:16)
I/flutter (14513): #10     WebSocketInterface.connect.<anonymous closure> (package:sip_ua/src/transports/websocket_interface.dart:92:9)
I/flutter (14513): #11     WebSocketImpl.co`

What can i do to resolve it?
