### ISSUE TITLE
Video call stream working in debug mode but not in release mode.

### ISSUE THREAD

**Issue by sahooamit1405** [flutter-webrtc/dart-sip-ua#275]
Implementing video call streaming using aestrisk . Working in debug mode but not in release mode. In release mode call is accepted and fails or disconnects immediately. No issue in debug mode. 

What I have tried : 
#Adding proguard rules.
#Changing build.grade defaultConfig .

**Comment by sahooamit1405** [comment]
jh

**Comment by Artemshchurev** [comment]
How you resolved this?
