### ISSUE TITLE
Call hangup instantly

### ISSUE THREAD

**Issue by treirouxel88** [flutter-webrtc/dart-sip-ua#279]
When trying to make a call :
E/flutter (13148): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Call initialize before setting the stream

The app registers fine.

**Comment by treirouxel88** [comment]
seems like the request is made wrong : 
(note that i replace all sensitive information with "----")

I/flutter (25834): [2022-04-29 10:28:27.979] Level.debug rtc_session.dart:1684 ::: emit "sdp"
I/flutter (25834): [2022-04-29 10:28:27.984] Level.debug rtc_session.dart:2292 ::: emit "sending" [request]
I/flutter (25834): [2022-04-29 10:28:27.995] Level.debug transport.dart:167 ::: send()
I/flutter (25834): [2022-04-29 10:28:27.999] Level.debug sip_message.dart:275 ::: Outgoing Message: v=0
I/flutter (25834): o=- 4506927224027681378 2 IN IP4 127.0.0.1
I/flutter (25834): s=-
I/flutter (25834): t=0 0
I/flutter (25834): a=group:BUNDLE 0
I/flutter (25834): a=extmap-allow-mixed
I/flutter (25834): a=msid-semantic: WMS 557214c7-1d6a-4e84-bd3a-ed0da452c126
I/flutter (25834): m=audio 38666 UDP/TLS/RTP/SAVPF 111 63 103 104 9 102 0 8 106 105 13 110 112 113 126
I/flutter (25834): c=IN IP4 77.205.143.233
I/flutter (25834): a=rtcp:9 IN IP4 0.0.0.0
I/flutter (25834): a=candidate:180044992 1 udp 2122260223 192.168.43.111 38666 typ host generation 0 network-id 3 network-cost 10
I/flutter (25834): a=candidate:559267639 1 udp 2122202367 ::1 56181 typ host generation 0 network-id 2
I/flutter (25834): a=candidate:1510613869 1 udp 2122129151 127.0.0.1 37110 typ host generation 0 network-id 1
I/flutter (25834): a=candidate:842163049 1 udp 1686052607 77.205.143.233 38666 typ srflx raddr 192.168.43.111 rport 38666 generation 0 network-id 3 network-cost 10
I/flutter (25834): a=candidate:1876313031 1 tcp 1518222591 ::1 60703 typ host tcptype passive generation 0 network-id 2
I/flutter (25834): a=candidate:344579997 1 tcp 1518149375 127.0.0.1 59068 typ host tcptype passive generation 0 network-id 1
I/flutter (25834): a=i
I/flutter (25834): [2022-04-29 10:28:28.3] Level.debug websocket_interface.dart:130 ::: send()
I/flutter (25834): [2022-04-29 10:28:28.10] Level.debug websocket_dart_impl.dart:49 ::: send: 
I/flutter (25834): 
I/flutter (25834): INVITE sip:----@---- SIP/2.0
I/flutter (25834): Via: SIP/2.0/WSS ymadfpsnyljk.invalid;branch=z9hG4bK1193479090000000
I/flutter (25834): Max-Forwards: 69
I/flutter (25834): To: <sip:----@---->
I/flutter (25834): From: "getuser" <sip:----@---->;tag=311f4go2ic
I/flutter (25834): Call-ID: 8l31571793058e65k420
I/flutter (25834): CSeq: 2975 INVITE
I/flutter (25834): Contact: <sip:----@ymadfpsnyljk.invalid;transport=wss;ob>
I/flutter (25834): Content-Type: application/sdp
I/flutter (25834): Session-Expires: 120
I/flutter (25834): Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO
I/flutter (25834): Supported: timer,ice,replaces,outbound
I/flutter (25834): User-Agent: Dart SIP Client v1.0.0
I/flutter (25834): Content-Length: 2295
I/flutter (25834): 
I/flutter (25834): v=0
I/flutter (25834): o=- 4506927224027681378 2 IN IP4 127.0.0.1
I/flutter (25834): s=-
I/flutter (25834): t=0 0
I/flutter (25834): a=group:BUNDLE 0
I/flutter (25834): a=extmap-allow-mixed
I/flutter (25834): a=msid-semantic: WMS 557214c7-1d6a-4e84-bd3a-ed0da452c126
I/flutter (25834): m=audio 38666 UDP/TLS/RTP/SAVPF 111 63 103 104 9 102 0 8 106 105 13 110 112 113 126
I/flutter (25834): c=IN IP4 77.205.143.233
I/flutter (25834): a=rtcp:9 IN IP4 0.0.0.0
I/flutter (25834): a=candidate:180044992 1 udp 2122260223 192.168.43.111 38666 typ host generation 0 network-id 3

tested on sip_ua 0.5.0 and in 0.5.1 (Android 8 Huawei EMUI 8 and Android 10), it happens on those 2 versions

**Comment by treirouxel88** [comment]
Okay found out what was my problem

**Comment by shingy92** [comment]
> Okay found out what was my problem

Hie @treirouxel88. Thanks for your update on this. I am having the same issue. How did you solve this ?

**Comment by treirouxel88** [comment]
i forgor
