### ISSUE TITLE
Hold/Unold not working for outgoing calls

### ISSUE THREAD

**Issue by RaviGaruda** [flutter-webrtc/dart-sip-ua#302]
**Describe the bug**
while doing outgoing calls, unable to hold/unhold calls(for incoming calls its works fine).

**To Reproduce**
1. Go to 'dialer screen'
2. Click on 'call button'
3. Scroll down to 'bottom options and try to hold the call'
4. Unable to hold and unhold call

**Expected behavior**
Call must be hold and again unhold after hold 

**Logs**
Level.debug rtc_session.dart:1097 ::: unhold()
Level.debug rtc_session.dart:1458 ::: _isReadyToReOffer() | internal WebRTC status not ready

**Comment by abhiddreambolix** [comment]
Dear Team, 

Please update hold & Unhold we are not able to hold outgoing call.

**Comment by RaviGaruda** [comment]
@abhiddreambolix have you found any solution?

**Comment by abhiddreambolix** [comment]
No it's not working

**Comment by abhiddreambolix** [comment]
I tried unhold is not working

**Comment by RaviGaruda** [comment]
same for me also, have you checked in incoming call?
