### ISSUE TITLE
Bluetooth Connect & Disconnect Multiple audio channel

### ISSUE THREAD

**Issue by abhiddreambolix** [flutter-webrtc/dart-sip-ua#303]
I am making an application which allow users to switch call from bluetooth headset to phone earpiece speaker, but its not working as expected, when i try to switch from bluetooth to earpiece speaker the voice comes from loud speaker.

**Comment by RaviGaruda** [comment]
@abhiddreambolix use this plugin https://pub.dev/packages/flutter_audio_manager

**Comment by abhiddreambolix** [comment]
Thank you so much its working now

**Comment by RaviGaruda** [comment]
is #302 working for you?

**Comment by abhiddreambolix** [comment]
Yes its also working as expected #302 @RaviGaruda

**Comment by RaviGaruda** [comment]
strange, in my case not works!!, which sip server you are using?

**Comment by eduardothiesen** [comment]
@abhiddreambolix I tried using the flutter_audio_manager alongside sip_ua but did not manage to make it work. Can you send a code sample please?
