### ISSUE TITLE
Video call app terminated 

### ISSUE THREAD

**Issue by harryandroiddev** [flutter-webrtc/dart-sip-ua#306]
While running android app in release mode ,Registered succesfully,  when i tap on video call button video screen pops for a second and then the app is terminated .(calling is working fine ).

**java.lang.IllegalArgumentException: Uknown native RtpTransceiverDirection type4**

But it is working on ios .

**Comment by dessy4oko** [comment]
Same exception on new android versions

**Comment by cloudwebrtc** [comment]
fixed https://github.com/flutter-webrtc/dart-sip-ua/pull/321
