### ISSUE TITLE
user get unregistered

### ISSUE THREAD

**Issue by MahmoudMamdoouh** [flutter-webrtc/dart-sip-ua#313]
**Describe the bug**
 when app is terminated user get unregistered

**Comment by Perondas** [comment]
This is desired behavior. A active connection to a server is only kept alive while the application is running.
Or do you mean something else?

**Comment by MahmoudMamdoouh** [comment]
> This is desired behavior. A active connection to a server is only kept alive while the application is running. Or do you mean something else?

yes that's what i meant

**Comment by Perondas** [comment]
If you want the connection to stay open, you will need to keep the application running, or move the library execution into some sort of background task. 
Both of these things are outside the scope of this library.
You can check out the [Background processes](https://docs.flutter.dev/development/packages-and-plugins/background-processes).
