### ISSUE TITLE
no sound when using callkit

### ISSUE THREAD

**Issue by treirouxel88** [flutter-webrtc/dart-sip-ua#320]
When i answer a call using callKit, i get no sound coming from the interlocutor.

the plugin i use is flutter_callkit_incoming.

**Comment by treirouxel88** [comment]
Fixed issue, i had to wait for the audio session

**Comment by eduardothiesen** [comment]
@treirouxel88 can you share an snippet of how you made it work on iOS using flutter_callkit_incoming?
