### ISSUE TITLE
Various issues with code quality 

### ISSUE THREAD

**Issue by Perondas** [flutter-webrtc/dart-sip-ua#323]
Some parts of the library need cleaning up. 
Some lints need to be implemented.
Some documentation needs to be added.
Some spelling mistakes need fixing.

**Comment by ghenry** [comment]
Thanks for this!

**Comment by Perondas** [comment]
I am currently looking into Nullability. It seems that a lot of things are kept nullable, even tough they are never used as such. Things like the Ua class are almost always set in the constructor, yet almost always kept as nullable. Leading to some "fun" returns like bool?.

**Comment by Perondas** [comment]
@cloudwebrtc could you please look over the comment I made in [d28d268](https://github.com/Perondas/dart-sip-ua/commit/d28d268f373c6e06b8a12f77c9f4b593fced891a) .
I am trying to understand if I am missing something, or this class just had a lot of dead code in it.
If it is the latter, was that intentional?
