### ISSUE TITLE
Is it possible to use only SIP without Websocket?

### ISSUE THREAD

**Issue by mkarabacak** [flutter-webrtc/dart-sip-ua#336]
I only need SIP application (no need IM, audio/video call). It is possible to get out flutter-webrtc integration ? 
I can pay for SIP only solution.

Thanks in advance,

**Comment by ghenry** [comment]
Hi @mkarabacak 

Sorry, this is a port of JsSIP, which is SIP over Websockets.

Thanks.

**Comment by mkarabacak** [comment]
Hi @ghenry , 
thanks for quick reply.
