### ISSUE TITLE
The getter 'this' isn't defined for the class 'AnsiColor'.

### ISSUE THREAD

**Issue by abdulhannan123** [flutter-webrtc/dart-sip-ua#347]
Hi, I am trying to run the example code, but I am unable to run it as it throws the following error:

**Error**
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/sip_ua-0.5.4/lib/src/logger.dart:133:16: Error: The getter 'this' isn't defined for the class 'AnsiColor'.
 - 'AnsiColor' is from 'package:sip_ua/src/logger.dart' ('/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/sip_ua-0.5.4/lib/src/logger.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'this'.
      return '$this$msg$ansiDefault';
               ^^^^

Any help will be appreciated.

**Version Infomation**
Flutter version: 3.0.5 
Dart SDK version: 2.17.6

**Comment by FeleConvo** [comment]
@Perondas This was introduced here: https://github.com/flutter-webrtc/dart-sip-ua/commit/88b83170bec550c4d6326dcb7fce24554751965a#diff-91837690ce0e2d558853d09d7cde1f9648cca326751fe2c437789882c0acfb67R133

**Comment by Perondas** [comment]
Oh, thanks @FeleConvo. Seems that that flew under the radar. Ill fix it it soon and push out a hotfix

**Comment by Perondas** [comment]
After some testing it seems that this is a issue that only occurs on older versions of flutter. On any more recent version (i tested with 3.5.0)  this code compile just fine, as it should. For some reason the older versions fail to correctly compile the interpolated string. 
Interpolation is however the preferred way to construct such strings. Therefore this is not an issue with dart-sip-ua.
