### ISSUE TITLE
Interactive testing with popular open source SIP servers.

### ISSUE THREAD

**Issue by cloudwebrtc** [flutter-webrtc/dart-sip-ua#38]
Test the following servers in order, register/un-register/(audio/video)call/hold/unhold, etc.

- [x] Asterisk
   Dockerfile https://github.com/flutter-webrtc/dockers/tree/main/asterisk
- [x] FreeSWITCH
- [x] OpenSIPS
- [x] reSiprocate
```bash
git clone https://github.com/resiprocate/resiprocate.git
cd resiprocate
autoreconf --install
./configure --with-ssl --with-repro CXXFLAGS="-I`pwd`/contrib/cajun/include"
cd repro
make
./repro
```
- [ ] Kamailio

**Comment by rlsutton1** [comment]
I'm can test Asterisk upon request. 

Master seems to work OK currently, although I haven't tested video

**Comment by cloudwebrtc** [comment]
Ah, thank you for telling me about these.
I think I need to find docker images of these popular sip servers so that they can be fully tested.

**Comment by sosaucily** [comment]
We are looking to test this package against any working configuration, so we can narrow down what works and what doesn't in our environment.

Can anyone point us to a hosted working environment with minimal setup where this dart-sip-ua package works, so we can ensure we have it configured properly on at least the flutter end? Thanks

**Comment by ghenry** [comment]
This was built and tested against the JsSIP test servers, tryit.jssip.net

It's also fine with our platform (SureVoIP). We use OpenSIPS WSS in front of FreeSWITCH. No issues.

What help do you need other than running the example app against any SIP platform that exposes WS or WSS?

Thanks, 
Gavin.

**Comment by sosaucily** [comment]
Thanks for the quick and helpful reply @ghenry 

We have been testing our product, an IoT device that among other features, makes SIP calls. We've used antisip.com for our testing until now. I see it runs Kamailio from the logging, but we don't have enough information to know if we can do SIP over websockets. And generally since there isn't much info on it's support for websockets or webrtc, we feel like we're shooting in the dark there.

So we'll try tryit.jssip.net and check out surevoip as well. We'll looking for a hosted solution to power our IoT product and take the amazing but complex webrtc/sip tech off our plate. 

Thanks!

**Comment by ghenry** [comment]
> So we'll try tryit.jssip.net and check out surevoip as well. We'll looking for a hosted solution to power our IoT product and take the amazing but complex webrtc/sip tech off our plate.
> 
> Thanks!

No problem. The key thing to remember is that this is a port of https://jssip.net/ to Dart (which we sponsored, but that makes no difference to this chat :-) ).

So docs on there and generally, "if the SIP provider works using https://tryit.jssip.net/ it should work with this".

The SIP service must have Secure Websockets to transport the SIP messaging over and support WebRTC media behind that. You could stick your own SIP Proxy and Media Proxy in front of a SIP provider if needed to. Then it gets a bit more complicated. You do need to know about SIP and WebRTC though to make use of all this. Not too trivial, but ask away.

Thanks.

**Comment by interteljapan** [comment]
> This was built and tested against the JsSIP test servers, tryit.jssip.net
> 
> It's also fine with our platform (SureVoIP). We use OpenSIPS WSS in front of FreeSWITCH. No issues.
> 
> What help do you need other than running the example app against any SIP platform that exposes WS or WSS?
> 
> Thanks,
> Gavin.

Does anyone have expertise to configure Opensip once installed on AWS server? RFC 8599 Push Notifications for incoming calls via SIP needs Opensips server. We like to engage paid services if you have experiences in making the Opensip config works. thanks

**Comment by ghenry** [comment]
We use the company that created OpenSo for consultancy
https://www.opensips-solutions.com/

The core team are amazing.

**Comment by interteljapan** [comment]
Hi Gavin, thank you.
