### ISSUE TITLE
EXCEPTION:On new version when call is incoming there is type exception with int? expires 

### ISSUE THREAD

**Issue by chuckwhisler** [flutter-webrtc/dart-sip-ua#393]
**Describe the bug**
On new version when call is incoming there is type error with int? expires
![image](https://github.com/flutter-webrtc/dart-sip-ua/assets/5471030/76942f4f-58dc-4f01-b347-f6186845cd13)

**To Reproduce**
Just get the incoming call it gives this error as descrbed above

**Expected behavior**
Incoming call screen should pop up

**System Infomation()**
Flutter SDK Version: 3.13.0
Target OS and Version: Android 33
Host OS and Version: Manjaro Linux x86_64

**Comment by chuckwhisler** [comment]
It's urgent please can you update ?

**Comment by cloudwebrtc** [comment]
@chuckwhisler can you try this branch?
https://github.com/flutter-webrtc/dart-sip-ua/pull/396

**Comment by chuckwhisler** [comment]
Thanks it's working now :+1:
