### ISSUE TITLE
Cannot resolve dependancies (intl 0.18.1 -> 0.19.0 fails) because of SIP_UA package

### ISSUE THREAD

**Issue by Theog75** [flutter-webrtc/dart-sip-ua#422]
**Describe the bug**
flutter pub upgrade  cannot update package ```intl``` due to sip_ua dependancy on ```intl 0.18.1``` , version ```0.19.0``` (the newest version is required by sip_ua.

```
Showing outdated packages.
[*] indicates versions that are not the latest available.

Package Name  Current  Upgradable  Resolvable  Latest  

direct dependencies:
intl          *0.18.1  *0.18.1     *0.18.1     0.19.0  

dev_dependencies: all up-to-date.
You are already using the newest resolvable versions listed in the 'Resolvable' column.
Newer versions, listed in 'Latest', may not be mutually compatible.
```

**To Reproduce**
1. run ```flutter pub upgrade```
2. the intl package cannot resolve dependancies

**Expected behavior**
flutter pub upgrade should resolve all dependancies, if other pckages will need ```intl 0.19.0``` the app will not work.

**System Infomation()**
Flutter SDK Version: 3.16.7
Target OS and Version: Android
Host OS and Version: Macos

**Comment by Theog75** [comment]
this is the output if I force upgrading intl to 0.19.0:
```
Because sip_ua 0.5.8 depends on intl ^0.18.0 and no versions of sip_ua match >0.5.8 <0.6.0, sip_ua ^0.5.8 requires intl ^0.18.0.
So, because comms depends on both intl ^0.19.0 and sip_ua ^0.5.8, version solving failed.
```

**Comment by Theog75** [comment]
it seems that this package is not maintained???
![image](https://github.com/flutter-webrtc/dart-sip-ua/assets/22218109/8e71e9d2-2923-4fce-ab6d-9bc838d6a6e4)

**Comment by cloudwebrtc** [comment]
fixed https://github.com/flutter-webrtc/dart-sip-ua/commit/ec6617230a05fad7db8ff4024eeeb97ce600d5d7

**Comment by Theog75** [comment]
Thanks, 
1. is there going to be a new release I can use in my flutter app?
2. what about the other packages (for example - error_parser is discontinued, flutter_webrtc cannot upgrade to latest  etc.
