### ISSUE TITLE
Request Timeout Error during SIP Registration

### ISSUE THREAD

**Issue by DarshanIncredere** [flutter-webrtc/dart-sip-ua#431]
Issue:
I'm encountering a "Request Timeout" error during the registration process of my SIP client in a Flutter application.

Steps to Reproduce:

Start the Flutter application.
Attempt SIP registration.
Observe the "Request Timeout" error.

Request:

REGISTER sip:xxx.com SIP/2.0
Via: SIP/2.0/WSS u712yopey496.invalid;branch=z9hG4b2349958341
Max-Forwards: 69
To: <sip:100@username.com>
From: "100" <sip:100@username.com>;tag=nnxil7vjnhk
Call-ID: 6ovgq1reo45097l817dd8s
CSeq: 1 REGISTER
Contact: null;+sip.ice;reg-id=1;+sip.instance="<urn:uuid:a898iuca-2795-449e-a195-57b7ccb9172c>";expires=3600
Expires: 3600
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO,NOTIFY
Supported: path,gruu,outbound
User-Agent: Dart SIP Client v1.0.0
Content-Length: 0

Error Logs:

flutter: [2024-03-12 12:17:44.713] Level.debug non_invite_client.dart:62 ::: Timer F expired for transaction z9hG4bK749958341
flutter: [2024-03-12 12:17:44.714] Level.debug sip_ua_helper.dart:183 ::: registrationFailed => Code: [408], Cause: Unavailable, Reason: Request Timeout

Flutter 3.19.0
Dart 3.3.0

Include any additional information that might be relevant to the issue.

Anyone in resolving this issue would be greatly appreciated!

Thank you in advance

**Comment by mikaelwills** [comment]
408 typically means your client didnt get a response from your server.
Is your server actually at username.com? 
Do you have username.com pointing to another ip in your hosts file?
