### ISSUE TITLE
Unable to Answer Calls with Locked Device

### ISSUE THREAD

**Issue by viniciusoliverrs** [flutter-webrtc/dart-sip-ua#433]
Description:
I am experiencing an issue where I am unable to answer incoming calls when my device is locked. When a call comes in, I am unable to complete the call while the device is locked. The call can only be initiated once the device is unlocked, as this is when Flutter is initialized.

Steps to Reproduce:
Lock the device.
Receive an incoming call.
Attempt to answer the call while the device is still locked.
Observe that the call cannot be completed.
Unlock the device.
Initiate the call successfully after the device is unlocked.
Expected Behavior:
I expect the call answering functionality to behave similarly to applications like WhatsApp, where incoming calls can be answered even when the device is locked. Users should be able to answer calls directly from the lock screen without needing to unlock the device first. This would enhance user experience and provide greater convenience when receiving calls.

Can anybody help me?

**Comment by JhunNormanAlonzo** [comment]
Hi, you can still receive call even the app is swiped out or closed ? is it running on background?

**Comment by viniciusoliverrs** [comment]
Hi, the solution I found was to create a service in the background. But it wasn't very good.

**Comment by eduardothiesen** [comment]
@viniciusoliverrs can you share you solution?

**Comment by dvxgit-jalonzo** [comment]
> Hi, the solution I found was to create a service in the background. But it wasn't very good,  because sometimes I can't retrieve the called object

I also got a solution for it , since it is running on background, i will invoke a method from background. it is stable now .

**Comment by eduardothiesen** [comment]
Can you share it? Thanks in advance

Em ter., 6 de ago. de 2024, 18:51, Alonzo ***@***.***>
escreveu:
