### ISSUE TITLE
How to setup a UDP connection for SIP credential?

### ISSUE THREAD

**Issue by ithieund** [flutter-webrtc/dart-sip-ua#442]
Hello,
I'm new to Flutter and this plugin too. I can see in the example app that it already support TCP and WS, but cannot see anywhere to setup the UDP connection because my VOIP server only support this kind of connection.
Please give me some advice or instruction to make it work.
Thank you very much!

**Comment by dineshpote26** [comment]
@ithieund  got solution?

**Comment by cloudwebrtc** [comment]
Since dart-sip-ua relies on webrtc as the media framework, the size of the generated SDP and Invite messages will exceed 1500 (MTU), so it is not suitable for UDP transmission.

**Comment by ithieund** [comment]
> Since dart-sip-ua relies on webrtc as the media framework, the size of the generated SDP and Invite messages will exceed 1500 (MTU), so it is not suitable for UDP transmission.

Thank you for your answer!

**Comment by sicunets** [comment]
> > Since dart-sip-ua relies on webrtc as the media framework, the size of the generated SDP and Invite messages will exceed 1500 (MTU), so it is not suitable for UDP transmission.
> 
> Thank you for your answer!

Did you do it for UDP?

**Comment by ithieund** [comment]
Yes I tried to find a lib for UDP but no luck.

**Comment by sicunets** [comment]
So you didn't work for UDP? Or try something else?
