### ISSUE TITLE
484 Address Incomplete

### ISSUE THREAD

**Issue by dineshpote26** [flutter-webrtc/dart-sip-ua#451]
Describe the bug
 Registration  status got Registered but when try to call other register number getting following error

To: <sip:1003@hostName>
I/flutter (  862): From: <sip:1001@hostName>;tag=o7qg3j69o4
Showing following error

I/flutter (  862): [2024-07-08 12:54:53.500] Level.debug tcp_socket.dart:160 ::: Received TcpSocket data
I/flutter (  862): [2024-07-08 12:54:53.501] Level.debug socket_transport.dart:274 ::: received binary message:
I/flutter (  862): 
I/flutter (  862): SIP/2.0 484 Address Incomplete

System Infomation()
Flutter SDK Version:2.5.0
Target OS and Version:0.5.1
Host OS and Version:iOS14

**Comment by dineshpote26** [comment]
Any suggestions

**Comment by cloudwebrtc** [comment]
484 may be related to the format of the SIP URI you called. Please make sure your URI is a reachable address.
