### ISSUE TITLE
call failed with cause: Code: [408], Cause: Unavailable, Reason: Request Timeout I/flutter ( 8964): callStateChanged Instance of 'Call' CallStateEnum.FAILED

### ISSUE THREAD

**Issue by Sankalpamokal** [flutter-webrtc/dart-sip-ua#458]
Getting status 408 request timeout while making call via TCP

**Comment by John251314** [comment]
Yest, I have same issues

**Comment by Sankalpamokal** [comment]
The issue might be bcaz of rport not matching. Is there any way to set static rport  while registering. Bcaz while registering we are getting dynamic rport which is not matching while making calls

**Comment by John251314** [comment]
> The issue might be bcaz of rport not matching. Is there any way to set static rport while registering. Bcaz while registering we are getting dynamic rport which is not matching while making calls resulting in call getting rejected from server due to port mismatch

No, I get this issues when registration to server; I don`t know what happened, It`s ok on the android Native, but I`m try registration using same account;

**Comment by viniciusoliverrs** [comment]
Any solution?

**Comment by BarakatMohamad** [comment]
@John251314 @viniciusoliverrs @Sankalpamokal @jbg @hiratake55  
Any solution?
