### ISSUE TITLE
Microphone gets muted when user locks screen while in call.

### ISSUE THREAD

**Issue by DooMMasteR** [flutter-webrtc/dart-sip-ua#468]
Whenever the user locks the phone screen (Android) while in a call, the devices microphone will be muted after a few moments.

1. Make call
2. lock screen while in call
3. wait for up to 10 seconds
4. the mic becomes muted until you unlock the phone again

I would have expected the call to stay functional.

Flutter SDK Version: 3.22.3
Target OS and Version: SDK 21
Host OS and Version: Android 14

**Comment by DooMMasteR** [comment]
Just any service? Our call/callui is currently not a service, this worked fine so far, but now it started failing on multiple devices.

**Comment by kritika6785** [comment]
<service android:name="id.flutter.flutter_background_service.BackgroundService"
            android:foregroundServiceType="microphone">
        <property android:name="android.app.PROPERTY_SPECIAL_USE_FGS_MICROPHONE"
            android:value="callerApp=ProcessRecord"/>
        </service>

**Comment by RaviGaruda** [comment]
@kritika6785 Awesome its working well

**Comment by RaviGaruda** [comment]
@kritika6785 have you made foreground service for keep running active call if user quite application during live voice call?

**Comment by kritika6785** [comment]
Not yet unable to keep the call active. Because sip get disconnected when
we terminate the application.

**Comment by reduxdj** [comment]
If you don't terminate the call when ice disconnects you can do this? we do.

**Comment by kritika6785** [comment]
@reduxdj how can we achieve this to stay connected to the call when the app is terminated?

**Comment by itsamit108** [comment]
> Give microphone permission as a background service, it will work.
> 

Can you please provide some sample codes , I'm finding it difficult to implement. Also some resources mentioned the flutter_foreground_task package to resolve this issue, what do you think?

**Comment by md-riaz** [comment]
I also want to know how to work around the microphone issue if the app goes background in an active call
