### ISSUE TITLE
Can't receive calls but can make calls using the example dart-sip-ua-example on android

### ISSUE THREAD

**Issue by tfn290181662** [flutter-webrtc/dart-sip-ua#474]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**System Infomation()**
Flutter SDK Version:
Target OS and Version:
Host OS and Version:

**Comment by kevalKathiriya258** [comment]
i facing same issue did you got any solution for this?

**Comment by mikaelwills** [comment]
In the world of open source, no ones going to help when your provide such little information.

**Comment by md-riaz** [comment]
same issue

**Comment by mikaelwills** [comment]
Just tested receiving and making calls using the example app on android with both a 3cx server and a FreePBX server using both WS and TCP. You need to provide more info.

**Comment by savan15** [comment]
i have faced something like same issue.

i have register my endpoint in TCP.
now when i place call from one endpoint to second endpoint then call not receive on second endpoint.

let's clarify more 

i have used two android device with this demo installed. now i have login with two sip account.

100 and 101 now i have place call from 100 to 101 but on 101 side call not received.

for my endpoint i have tested on linephone application. it's work fine call are work fine.

**Comment by mikaelwills** [comment]
@savan15 

What do you SIP logs say

**Comment by savan15** [comment]
@mikaelwills 
there is no any error on show android device. when i see run windows in android studio.

**Comment by mikaelwills** [comment]
@savan15 dart-sip-ua outputs SIP flow logs, just make sure to uncomment  'Logger.level = Level.warning;'
in the main.dart of the example app.

Those logs will tell you what your problem is, everyone else here should be posting their logs too.

**Comment by savan15** [comment]
also one more thing i want to clear.

for use this library does my endpoint need to be enable webrtc?
@mikaelwills

**Comment by savan15** [comment]
here are that log. when i place call that time this log are seeing i have.

D/FlutterWebRTCPlugin( 7415): onIceCandidate

I/flutter ( 7415): input => , rule => Request_Response

I/flutter ( 7415): Format exception: Expected !, %, ', 'ACK', 'BYE', 'CANCEL', 'INVITE', 'NOTIFY', 'OPTIONS', 'REFER', 'REGISTER', 'SUBSCRIBE', *, +, -, ., SIP, _, `, alphanum, ~ but found end of file
I/flutter ( 7415): [2024-09-22 16:53:35.373] Level.error parser.dart:32 ::: parseMessage() | error parsing first line of SIP message: ""
D/FlutterWebRTCPlugin( 7415): onIceGatheringChangeCOMPLETE

**Comment by mikaelwills** [comment]
> also one more thing i want to clear.
> 
> for use this library does my endpoint need to be enable webrtc? @mikaelwills

Yes

**Comment by mikaelwills** [comment]
> here are that log. when i place call that time this log are seeing i have.
> 
> D/FlutterWebRTCPlugin( 7415): onIceCandidate
> 
> I/flutter ( 7415): input => , rule => Request_Response
> 
> I/flutter ( 7415): Format exception: Expected !, %, ', 'ACK', 'BYE', 'CANCEL', 'INVITE', 'NOTIFY', 'OPTIONS', 'REFER', 'REGISTER', 'SUBSCRIBE', *, +, -, ., SIP, _, `, alphanum, ~ but found end of file I/flutter ( 7415): [2024-09-22 16:53:35.373] Level.error parser.dart:32 ::: parseMessage() | error parsing first line of SIP message: "" D/FlutterWebRTCPlugin( 7415): onIceGatheringChangeCOMPLETE

Yea ive come across this issue before, and unfortunately its stumped me. 

What I noticed with this is a SIP message seems to be split into two somewhere.
Half of it comes in, dart-sip-ua detects that the body is less that the content length header so it throws it out.
The second half of the message comes in and the parser can't parse it because it doesnt start with the correct info, so you get that error you pasted.

Anytime ive come across this, ive logged the outgoing message at the very edge of the plugin as it gets sent on the socket and just when it comes in and I can't see anywhere within the package where it might be split in two.

My only theory on this is that possibly the message is too big for a packet so the network infrastructure splits it up. 

Maybe we could implement something where if a message comes in thats two short, it could wait for the next one and pair them up, but we shouldnt need to do this... any thoughts @cloudwebrtc ?

**Comment by savan15** [comment]
Ok, 
Can we setup any custom codec in this library?

**Comment by BarakatMohamad** [comment]
@savan15 @mikaelwills @md-riaz any thing for this error I receive the call but I can not make that ????

**Comment by BarakatMohamad** [comment]
@mikaelwills  any ideas?

**Comment by savan15** [comment]
@BarakatMohamad 
As we have debug on our server side. 
We have found webrtc option on endpoint are not enabled. so we have enable it and issue has been resolved.

On your case need to check endpoint configuration and call server configuration.

**Comment by Kay-coding** [comment]
> webrtc 选项
Hello, I also encountered the same problem as you. How to enable the webrtc option on the endpoint? Please tell me. Thank you very much.

**Comment by Kay-coding** [comment]
@savan15 
Hello, I also encountered the same problem as you. How to enable the webrtc option on the endpoint? Please tell me. Thank you very much.

**Comment by md-riaz** [comment]
i am using ctxSip web phone easily with my fusionpbx server, but in flutter, i am debugging calls in chrome as a web app with flutter, but after the initial registration websocket connection, i see no invitation when fusionpbx calls the flutter agent. I find no reason why js websocket works but not in flutter webrtc websocket connection.

**Comment by ygor-dextak** [comment]
Have you made any progress with this? I have the same problem using Fusion PBX, previously I used Asterisk and everything worked fine

**Comment by md-riaz** [comment]
@BarakatMohamad Hi,
Did you receive incoming calls using fusionpbx server?
Can you share your example repo to see what I missed ?

**Comment by md-riaz** [comment]
It seems calls with WS transport type works for fusion pbx
