### ISSUE TITLE
No media on incoming call

### ISSUE THREAD

**Issue by wishwelloklu** [flutter-webrtc/dart-sip-ua#478]
I am running my sip for both incoming and outgoing call. The outgoing works perfectly but with incoming calls. I don't get audio and the other party can hear me speak and then the call hangs up on the 15th sec with call ended with cause: Code: [408], Cause: RTP Timeout, Reason: RTP Timeout

**Comment by viniciusoliverrs** [comment]
Hi, how did you resolve this issue?

**Comment by wishwelloklu** [comment]
> Hi, how did you resolve this issue?

I haven't. I closed the issue by accident

**Comment by wishwelloklu** [comment]
Please, some should look at this answerCall method of mine and see if I am doing something wrong


` Future answerCall() async {
    _callId ??= _lastCallId;
    await AppPermission.requestMicrophonePermission();

    try {
    

      final pcConfig = {
        'iceServers': [
          {
            'urls': 'stun:stun.l.google.com:19302'
          }, // STUN server for NAT traversal
          {
            'urls':
                'turn:turnserver.example.org', // TURN server for fallback relaying
            'username': 'user',
            'credential': 'pass'
          }
        ],
        'iceTransportPolicy': 'all', // Options: 'all' or 'relay'
        'bundlePolicy':
            'balanced', // Options: 'balanced', 'max-compat', 'max-bundle'
        'rtcpMuxPolicy': 'require', // Options: 'require' or 'negotiate'
        'sdpSemantics': 'unified-plan' // Options: 'unified-plan' or 'plan-b'
      };
      final rtcConstraints = {
        'mandatory': {
          'OfferToReceiveAudio':
              true, // Request an audio stream in SDP offer/answer
          'OfferToReceiveVideo': false, // Don't request a video stream
        },
        'optional': [
          {'DtlsSrtpKeyAgreement': true}, // Enable SRTP for secure media
          {'RtpDataChannels': true} // Enable RTP-based data channels
        ]
      };

      final mediaContraints = {'audio': true, 'video': false};

      final mediaStream =
          await navigator.mediaDevices.getUserMedia(mediaContraints);
      final peerConnection =
          await createPeerConnection(pcConfig, rtcConstraints);
      final audioTrack = mediaStream.getAudioTracks()[0];
      peerConnection.addTrack(audioTrack, mediaStream);
      peerConnection.getRemoteDescription();
      final call = helper.findCall(_callId!);
      call?.answer(helper.buildCallOptions(true), mediaStream: mediaStream);
    } catch (e) {
      if (kDebugMode) {
        print('erreee: $e');
      }
    }
  }
`

**Comment by wishwelloklu** [comment]
Please, some should look at this answerCall method of mine and see if I am doing something wrong
``
 Future answerCall() async {
    _callId ??= _lastCallId;
    await AppPermission.requestMicrophonePermission();

    try {
    

      final pcConfig = {
        'iceServers': [
          {
            'urls': 'stun:stun.l.google.com:19302'
          }, // STUN server for NAT traversal
          {
            'urls':
                'turn:turnserver.example.org', // TURN server for fallback relaying
            'username': 'user',
            'credential': 'pass'
          }
        ],
        'iceTransportPolicy': 'all', // Options: 'all' or 'relay'
        'bundlePolicy':
            'balanced', // Options: 'balanced', 'max-compat', 'max-bundle'
        'rtcpMuxPolicy': 'require', // Options: 'require' or 'negotiate'
        'sdpSemantics': 'unified-plan' // Options: 'unified-plan' or 'plan-b'
      };
      final rtcConstraints = {
        'mandatory': {
          'OfferToReceiveAudio':
              true, // Request an audio stream in SDP offer/answer
          'OfferToReceiveVideo': false, // Don't request a video stream
        },
        'optional': [
          {'DtlsSrtpKeyAgreement': true}, // Enable SRTP for secure media
          {'RtpDataChannels': true} // Enable RTP-based data channels
        ]
      };

      final mediaContraints = {'audio': true, 'video': false};

      final mediaStream =
          await navigator.mediaDevices.getUserMedia(mediaContraints);
      final peerConnection =
          await createPeerConnection(pcConfig, rtcConstraints);
      final audioTrack = mediaStream.getAudioTracks()[0];
      peerConnection.addTrack(audioTrack, mediaStream);
      peerConnection.getRemoteDescription();
      final call = helper.findCall(_callId!);
      call?.answer(helper.buildCallOptions(true), mediaStream: mediaStream);
    } catch (e) {
      if (kDebugMode) {
        print('erreee: $e');
      }
    }
  }

``
