### ISSUE TITLE
Transport type UDP

### ISSUE THREAD

**Issue by sicunets** [flutter-webrtc/dart-sip-ua#482]
Can you add a new feature for TransportType? I need Transport type UDP.

**Comment by Tin-Primas** [comment]
By default WebRTC use UDP wdym

**Comment by sicunets** [comment]
Here i am getting transport type ws & tcp. So how can i manage it to use udp?

**Comment by mikaelwills** [comment]
We use a WS or TCP connection for the signalling processs to initiate or terminate a session (sip messages).
Once the session is connected WebRTC transmits the actual media (audio/video) over UDP.

Why would you want to use UDP for the signalling step?  (Genuine question) 
Also do you realise what UDP is and how much is needed to set it up, packet ordering, error checking, reliability timeouts, flow control, security etc etc

**Comment by sicunets** [comment]
> We use a WS or TCP connection for the signalling processs to initiate or terminate a session (sip messages). Once the session is connected WebRTC transmits the actual media (audio/video) over UDP.
> 
> Why would you want to use UDP for the signalling step? (Genuine question) Also do you realise what UDP is and how much is needed to set it up, packet ordering, error checking, reliability timeouts, flow control, security etc etc

I am trying to build softphone app. I need to use sip server and transport type udp. I don't have deep knowledge about this. I saw that webrtc use udp connection. Can you please give more details about this or resource?

**Comment by ushodmonov** [comment]
+++

I need Transport type UDP.

**Comment by TaraCybertouch** [comment]
I Need also transport type UDP

**Comment by mikaelwills** [comment]
> > We use a WS or TCP connection for the signalling processs to initiate or terminate a session (sip messages). Once the session is connected WebRTC transmits the actual media (audio/video) over UDP.
> > Why would you want to use UDP for the signalling step? (Genuine question) Also do you realise what UDP is and how much is needed to set it up, packet ordering, error checking, reliability timeouts, flow control, security etc etc
> 
> I am trying to build softphone app. I need to use sip server and transport type udp. I don't have deep knowledge about this. I saw that webrtc use udp connection. Can you please give more details about this or resource?

@sicunets Why do you "need to use... transport type udp"? What is the name of the sip server that is forcing you to use udp?
If you read my comment again, yes webRTC uses udp for sending the audio/video data packets, AFTER WS or TCP is used to initiate the call with SIP signalling.
The transport types WS and TCP that you see in this package are only for the SIP signally processes, before webRTC uses UDP to send the content of the call.

@ushodmonov @TaraCybertouch read the above and explain what is making you need udp for sip signalling

**Comment by eliasDniel** [comment]
Ayuda necesito el transporte udp
