### ISSUE TITLE
SIP Calls on Samsung S24 Ultra in Production Mode

### ISSUE THREAD

**Issue by viniciusoliverrs** [flutter-webrtc/dart-sip-ua#483]
Description:
We are experiencing a specific issue on the Samsung S24 Ultra related to SIP calls. When an incoming call is received and the application is started, audio is not transmitted correctly, resulting in a timeout or authentication error. Interestingly, SIP registration works without issues.

Observed Behavior:

Scenario: Production Mode
Action: Answering a SIP call
Result:
Audio is not transmitted.
Timeout or authentication errors occur.
Testing Scenario:

Debug Mode: The issue does not occur, and calls function normally.
Possible Causes:

Suspected limitations related to the device kernel or operating system, potentially affecting packet size.
Steps Taken:

Verified SIP configuration.
Tested on other devices (normal results).
Analyzed logs during calls (no clear error identified).
Reviewed app permissions and network settings.
Request for Help:

Has anyone encountered a similar issue?
Any suggestions for resolving this problem?
Thank you for your assistance!

**Comment by mikaelwills** [comment]
Have a look at what audio codecs are being sent in the SDP compared to what audio codecs your PBX accepts

**Comment by BarakatMohamad** [comment]
@mikaelwills  I asked you many time , why you did not replaying me ?
