### ISSUE TITLE
Bug Report for dart-sip-ua v1.0.0

### ISSUE THREAD

**Issue by himanshujjp** [flutter-webrtc/dart-sip-ua#499]
Describe the Bug
In dart-sip-ua version 1.0.0, there are issues with the Hold and Speaker functionalities on multiple platforms (Android, Web, Linux). These features work correctly in version 0.6.0, but after updating to 1.0.0, Hold and Speaker do not function as expected.

To Reproduce
Steps to reproduce the issue:

Go to the call screen in the application.
During an active call, attempt to activate Hold.
Attempt to switch audio output to Speaker.
Observe the error or unexpected behavior.
Expected Behavior
The Hold button should pause the call, and the Speaker button should switch the audio output to the device's speaker.

System Information

Flutter SDK Version: 3.24.4 (Stable Channel)
Target OS and Version: Android 13, Web, Linux
Host OS and Version: Ubuntu 20.04

**Comment by mikaelwills** [comment]
Yea theres another issue up for this, I'm looking into fixing it.
