### ISSUE TITLE
Dependency resolution bug

### ISSUE THREAD

**Issue by wishwelloklu** [flutter-webrtc/dart-sip-ua#502]
**Describe the bug**
Dependency resolution fails when I use the new flutter_webrtc

**Output**
Because sip_ua 1.0.0 depends on flutter_webrtc ^0.10.4 and no versions of sip_ua match >1.0.0 <2.0.0, sip_ua ^1.0.0 requires flutter_webrtc ^0.10.4.
So, because rippledesk depends on both sip_ua ^1.0.0 and flutter_webrtc ^0.12.1+hotfix.1, version solving failed.

**Comment by Irie-Saint** [comment]
Same issue on my side, impossible to update **web** to version 1+ because **sip_ua 1.0.0** depends on it
So, most of my plugin's project are not updated because they depend on **web 1+**
Same for **webrtc**

Any solution?

**Comment by wishwelloklu** [comment]
No solution

**Comment by mikaelwills** [comment]
@wishwelloklu just to confirm this was using flutter_webrtc: 0.12.4?

**Comment by mikaelwills** [comment]
@wishwelloklu  @Irie-Saint  have just commited dependency updates to the latest flutter_webRTC. 
Will be pushing a new release shortly

**Comment by wishwelloklu** [comment]
> @wishwelloklu  @Irie-Saint  have just commited dependency updates to the latest flutter_webRTC. 
> 
> Will be pushing a new release shortly

Ok

**Comment by mikaelwills** [comment]
@wishwelloklu  its up now, let me know how it goes

**Comment by wishwelloklu** [comment]
@mikaelwills  Alright. I will check it out

**Comment by mikaelwills** [comment]
> @mikaelwills Alright. I will check it out

@wishwelloklu  In my company, im literally in the middle of updating all our repo's to the latest dart, flutter and all th dependencies.
Then i'lll be bringing in this package ontop of all that to make it work so it should be good with the latest out there.

**Comment by wishwelloklu** [comment]
@mikaelwills Thanks. It works

**Comment by wishwelloklu** [comment]
@mikaelwills How can I access the data in the sip header when I get an incoming call?
I tried this ```_call?.session.remote_identity?.uri?.getHeader(null)``` but I got null
