### ISSUE TITLE
Level.error event_manager.dart:111 ::: type 'int' is not a subtype of type 'String'

### ISSUE THREAD

**Issue by qinheqin** [flutter-webrtc/dart-sip-ua#506]
_helper.register()  注册报错
![image](https://github.com/user-attachments/assets/3da07674-84d5-44a7-9677-73450cf7cc6e)
错误位置
![image](https://github.com/user-attachments/assets/03eacc4f-95ea-4baf-809c-079c4a1d18e9)
       expires ??= _expires
==》
       expires ??= _expires.toString();

**Comment by mikaelwills** [comment]
@qinheqin  is it the error: e that its complaining about?  might be as simple as another error: e.toString()

**Comment by victortive** [comment]
The correct solution here is 

```dart
expires = num.tryParse(expires.toString() ?? 0;
```

since expires is expected to be an integer eventually. Since tryParse expects a string, just convert it `toString()` when necessary

**Comment by mikaelwills** [comment]
> The correct solution here is
> 
> ```dart
> expires = num.tryParse(expires.toString()) ?? 0;
> ```
> 
> since expires is expected to be an integer eventually. Since tryParse expects a string, just convert it `toString()` when necessary

ah duh, yea i was looking at the error catch. Merged!
