### ISSUE TITLE
When running the demo, I can make calls but cannot receive calls, and there are no warnings or prompts in the logs.

### ISSUE THREAD

**Issue by Kay-coding** [flutter-webrtc/dart-sip-ua#507]
**Describe the bug**
When I run the sip_ua example, I can make a call successfully, but I cannot answer the call. I have turned on the alarm log printing, but I have not received any received message logs. The device has been successfully registered. Device b calls device a, and device b can make a call but there is no one. When answering, the a device cannot receive any called messages. The server can use other clients such as linphone to dial and answer normally. It is confirmed that there is no problem on the server. This problem has been bothering me for a month. Please help me. Thank you very much.

**To Reproduce**

**Expected behavior**
When running the demo, I can make calls but cannot receive calls, and there are no warnings or prompts in the logs.

**System Infomation()**
Flutter SDK Version: 3.23.0-0.1.pre
Target OS and Version: iphone 13  18.1.1
Host OS and Version:Mac OS 14.4

**Comment by Kay-coding** [comment]
@mikaelwills

**Comment by ygor-dextak** [comment]
Have you made any progress with this? I have the same problem using Fusion PBX, previously I used Asterisk and everything worked fine

**Comment by mikaelwills** [comment]
@Kay-coding  When you say "I have turned on the alarm log printing,"
Do you mean you uncomment   'Logger.level = Level.warning;' in the example apps main.dart?

It's impossible to help without any sort of logging.

**Comment by ygor-dextak** [comment]
I have this line uncommented, but I simply don't receive any logs. I used asterisk previously and it worked correctly, but now using fusionpbx I can't receive calls, can you tell me if there can be any specific configuration when connecting to the server? Because I tested it with other softphone applications and everything works

**Comment by mikaelwills** [comment]
> I have this line uncommented, but I simply don't receive any logs. I used asterisk previously and it worked correctly, but now using fusionpbx I can't receive calls, can you tell me if there can be any specific configuration when connecting to the server? Because I tested it with other softphone applications and everything works

@ygor-dextak  Unfortunately i have no experience with using fusionPBX, you're issue is too unspecific to for me to provide any kind of help.
If you've uncommented the logger level warning and no print outs at all from this package then I simply can't help you and it's a PBX issue that is blocking calls to the extension for some reason. 
You might need to go on the fusionPBX forums if they have any.

**Comment by ygor-dextak** [comment]
I don't think it's a PBX problem because I use the same extension in other apps and it works normally

**Comment by Kay-coding** [comment]
> @Kay-coding When you say "I have turned on the alarm log printing," Do you mean you uncomment 'Logger.level = Level.warning;' in the example apps main.dart?
> 
> It's impossible to help without any sort of logging.

yes，i  uncomment 'Logger.level = Level.warning;'，I use linphone to call sip_up, and there is no prompt in the android studio log. At that time, I went to the dialpad page, but I can call linphone. When linphone calls sip_up, I can see that it is waiting for sip_up to answer. I can call out, but there is no log message or prompt for sip_up. I'm running your example

**Comment by Kay-coding** [comment]
In addition, I run the example in siprix_voip_sdk and use siprix_voip_sdk to test my sip server. I can make normal calls and receive responses. After sip_ua is successfully registered, I can only make calls but cannot receive responses. However, I can feel that I can receive but the reception is not processed. The received message is because it is dialed using linphone and it is waiting for sip_ua to answer.

**Comment by Kay-coding** [comment]
Forgot to explain that I am using tcp connection. Wss connection can make calls but cannot answer calls.

**Comment by Kay-coding** [comment]
![image](https://github.com/user-attachments/assets/727c3d1b-bda8-425f-9d12-5a126db01517)
![image](https://github.com/user-attachments/assets/ec7ad669-ed87-435d-aaeb-097955042e4c)
I found that the registration connection method of sip_ua is different from others. The sip registered by linphone will bring the network IP, but the sip_ua registration will not bring the IP but only the host. This may be the reason why the answer cannot be received. Check the picture and you can see a It is registered by linphone, b is registered by sip_ua; and I found that the transportType is configured with tcp, and what I see on the server is indeed UDP, which is a bit strange.

**Comment by Kay-coding** [comment]
settings.contact_uri =
        'sip:xxxxxx@${await NetworkInfo().getWifiIP()};transport=tcp';
I think I should have found the reason why I cannot receive calls. In the registration configuration, contact_uri should configure the dynamic IP of this device. After configuration, I can receive and answer calls using linphone, but a new problem has arisen. After clicking monitor, 488 is reported. mistake
![image](https://github.com/user-attachments/assets/e92f4524-1fde-4858-867c-7dc850f6b561)
@mikaelwills

**Comment by Kay-coding** [comment]
I/flutter ( 9154): dialpad callStateChanged=========>null
I/flutter ( 9154): dialpad callStateChanged=========>CallStateEnum.CALL_INITIATION
I/flutter ( 9154): dialpad callStateChanged=========>Code: [null], Cause: null, Reason: null
I/flutter ( 9154): dialpad callStateChanged=========>CallStateEnum.PROGRESS
I/org.webrtc.Logging( 9154): EglBase14Impl: Using OpenGL ES version 2
I/org.webrtc.Logging( 9154): EglRenderer: Initializing EglRenderer
D/mali_winsys( 9154): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
I/org.webrtc.Logging( 9154): EglBase14Impl: Using OpenGL ES version 2
I/org.webrtc.Logging( 9154): EglRenderer: Initializing EglRenderer
D/mali_winsys( 9154): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
V/AudioManager( 9154): querySoundEffectsEnabled...
I/FlutterWebRTCPlugin( 9154): getUserMedia(audio): mandatory: [], optional: [googNoiseSuppression: true, googEchoCancellation: true, echoCancellation: true, googEchoCancellation2: true, googDAEchoCancellation: true]
D/FlutterWebRTCPlugin( 9154): MediaStream id: a4c95032-376c-4057-8d42-b6cb93453f61
V/AudioManager( 9154): getMode...
V/AudioManager( 9154): isMicrophoneMute... 
V/AudioManager( 9154): isSpeakerphoneOn: false
I/AudioManager( 9154): setMicrophoneMute false
I/AudioManager( 9154): requestAudioFocus focusRequest
I/AudioManager( 9154): setMode 3
I/AudioManager( 9154): stopBluetoothSco
I/AudioManager( 9154): setSpeakerphoneOn: true
D/FlutterWebRTCPlugin( 9154): peerConnectionSetRemoteDescription(): WEBRTC_SET_REMOTE_DESCRIPTION_ERROR: Failed to set remote offer sdp: Called with SDP without DTLS fingerprint.
I/flutter ( 9154): dialpad callStateChanged=========>Code: [488], Cause: WebRTC Error, Reason: SetRemoteDescription(offer) failed
I/flutter ( 9154): dialpad callStateChanged=========>CallStateEnum.FAILED
I/flutter ( 9154): [2024-12-19 15:09:55.344] Level.error rtc_session.dart:663 ::: emit "peerconnection:setremotedescriptionfailed" [error:Unable to RTCPeerConnection::setRemoteDescription: peerConnectionSetRemoteDescription(): WEBRTC_SET_REMOTE_DESCRIPTION_ERROR: Failed to set remote offer sdp: Called with SDP without DTLS fingerprint.]
E/flutter ( 9154): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Assertion failed: "peerconnection.setRemoteDescription() failed"
E/flutter ( 9154): #0      RTCSession.answer (package:sip_ua/src/rtc_session.dart:666:7)
E/flutter ( 9154): <asynchronous suspension>
E/flutter ( 9154): 
D/FlutterWebRTCPlugin( 9154): onConnectionChangeCLOSED
I/AudioManager( 9154): setMode 0
I/flutter ( 9154): [2024-12-19 15:09:55.389] Level.error sip_ua_helper.dart:465 ::: Call 235c7d40-387b-123e-6f88-024982bbf056Q4BSKyeDFe5Fj not found!
I/AudioManager( 9154): setMicrophoneMute false
I/AudioManager( 9154): setSpeakerphoneOn: false
I/AudioManager( 9154): abandonAudioFocusRequest focusRequest
V/AudioManager( 9154): querySoundEffectsEnabled...
I/FlutterWebRTCPlugin( 9154): getUserMedia(audio): mandatory: [], optional: [googNoiseSuppression: true, googEchoCancellation: true, echoCancellation: true, googEchoCancellation2: true, googDAEchoCancellation: true]
D/FlutterWebRTCPlugin( 9154): MediaStream id: b3fa0bbd-4de1-4895-9ce2-0603feb138e2
V/AudioManager( 9154): getMode...
V/AudioManager( 9154): isMicrophoneMute... 
V/AudioManager( 9154): isSpeakerphoneOn: false
I/AudioManager( 9154): setMicrophoneMute false
E/flutter ( 9154): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Instance of 'InvalidStateError'
E/flutter ( 9154): #0      RTCSession.answer (package:sip_ua/src/rtc_session.dart:498:7)
E/flutter ( 9154): #1      Call.answer (package:sip_ua/src/sip_ua_helper.dart:544:14)
E/flutter ( 9154): #2      _MyCallScreenWidget._handleAccept (package:dart_sip_ua_example/src/callscreen.dart:225:11)
E/flutter ( 9154): <asynchronous suspension>
E/flutter ( 9154): 
I/AudioManager( 9154): requestAudioFocus focusRequest
I/AudioManager( 9154): setMode 3
I/AudioManager( 9154): stopBluetoothSco
I/AudioManager( 9154): setSpeakerphoneOn: true

**Comment by mikaelwills** [comment]
@Kay-coding awesome, thank you for providing enough information.

This is your problem: 
WEBRTC_SET_REMOTE_DESCRIPTION_ERROR: Failed to set remote offer sdp: Called with SDP without DTLS fingerprint.]

My label is correct in that your problem isn't a bug with this package its your server not configured correctly for webRTC. Basically what the above means is that your server is not sending a DTLS fingerprint inside the SDP when inviting the sip_ua client to start a call. 

The reason why calls in siprix are working is because siprix doesnt use WebRTC. 

WebRTC uses encryption by Default, all WebRTC communications (audio, video, and data) are encrypted using DTLS and SRTP, ensuring secure communication. Your PBX must be configured to use DTLS/SRTP when calling sip_ua.

**Comment by Kay-coding** [comment]
> @Kay-coding awesome, thank you for providing enough information.
> 
> This is your problem: WEBRTC_SET_REMOTE_DESCRIPTION_ERROR: Failed to set remote offer sdp: Called with SDP without DTLS fingerprint.]
> 
> My label is correct in that your problem isn't a bug with this package its your server not configured correctly for webRTC. Basically what the above means is that your server is not sending a DTLS fingerprint inside the SDP when inviting the sip_ua client to start a call.
> 
> The reason why calls in siprix are working is because siprix doesnt use WebRTC.
> 
> WebRTC uses encryption by Default, all WebRTC communications (audio, video, and data) are encrypted using DTLS and SRTP, ensuring secure communication. Your PBX must be configured to use DTLS/SRTP when calling sip_ua.

Thank you very much for your patient answer. We will deal with the server configuration problem and give you feedback after solving it. Thank you again

**Comment by nikhilingle1302** [comment]
@Kay-coding @mikaelwills bro im able to register using the sip_ua GitHub example but not able to make calls can you help me?
when im trying to call this log is comming 
`destination uri: 102@13.201.19.118:5060
`
```

I/FlutterWebRTCPlugin( 3926): getUserMedia(audio): mandatory: [], optional: [googNoiseSuppression: true, googEchoCancellation: true, echoCancellation: true, googEchoCancellation2: true, googDAEchoCancellation: true]
D/FlutterWebRTCPlugin( 3926): MediaStream id: 1f1545c2-aad5-47fe-bb3e-8080d81d92aa
I/AudioManager( 3926): In isSpeakerphoneOn(), calling application: com.example.new_sip_ua
I/AudioManager( 3926): In stopBluetoothSco(), calling application: com.example.new_sip_ua
I/AudioManager( 3926): In setSpeakerphoneOn(), on: true, calling application: com.example.new_sip_ua
I/flutter ( 3926): call id :dvhv782950259739e1850555843041
I/org.webrtc.Logging( 3926): EglBase14Impl: Using OpenGL ES version 2
I/org.webrtc.Logging( 3926): EglRenderer: Initializing EglRenderer
I/org.webrtc.Logging( 3926): WebRtcAudioRecordExternal: enableBuiltInAEC(true)
I/org.webrtc.Logging( 3926): WebRtcAudioEffectsExternal: setAEC(true)
I/org.webrtc.Logging( 3926): WebRtcAudioRecordExternal: enableBuiltInNS(true)
I/org.webrtc.Logging( 3926): WebRtcAudioEffectsExternal: setNS(true)
I/org.webrtc.Logging( 3926): NetworkMonitor: Start monitoring with native observer -5476376617324803488 fieldTrialsString: 
I/org.webrtc.Logging( 3926): NetworkMonitorAutoDetect: Network handle: 553161510925 becomes available: 128
D/FlutterWebRTCPlugin( 3926): onIceGatheringChangeGATHERING
I/org.webrtc.Logging( 3926): NetworkMonitorAutoDetect: handle: 553161510925 capabilities changed: [ Transports: WIFI Capabilities: NOT_METERED&INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&VALIDATED&NOT_ROAMING&FOREGROUND&NOT_CONGESTED&NOT_SUSPENDED LinkUpBandwidth>=330179Kbps LinkDnBandwidth>=407628Kbps SignalStrength: -57 AdministratorUids: [] RequestorUid: -1 RequestorPackageName: null]
I/org.webrtc.Logging( 3926): EglBase14Impl: Using OpenGL ES version 2
I/org.webrtc.Logging( 3926): NetworkMonitorAutoDetect: handle: 553161510925 link properties changed
I/org.webrtc.Logging( 3926): EglRenderer: Initializing EglRenderer
4
D/FlutterWebRTCPlugin( 3926): onIceCandidate
I/chatty  ( 3926): uid=10248(com.example.new_sip_ua) signaling_threa identical 3 lines
D/FlutterWebRTCPlugin( 3926): onIceCandidate
I/flutter ( 3926): input => , rule => Request_Response
I/flutter ( 3926): Format exception: Expected !, %, ', 'ACK', 'BYE', 'CANCEL', 'INVITE', 'NOTIFY', 'OPTIONS', 'REFER', 'REGISTER', 'SUBSCRIBE', *, +, -, ., SIP, _, `, alphanum, ~ but found end of file
I/flutter ( 3926): [2025-01-27 19:19:08.371] Level.error parser.dart:32 ::: parseMessage() | error parsing first line of SIP message: ""
I/org.webrtc.Logging( 3926): EglRenderer: Duration: 4010 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging( 3926): EglRenderer: Duration: 4004 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
```

**Comment by mikaelwills** [comment]
> [@Kay-coding](https://github.com/Kay-coding) [@mikaelwills](https://github.com/mikaelwills) bro im able to register using the sip_ua GitHub example but not able to make calls can you help me? when im trying to call this log is comming `destination uri: 102@13.201.19.118:5060 `
> 
> ```
> 
> I/FlutterWebRTCPlugin( 3926): getUserMedia(audio): mandatory: [], optional: [googNoiseSuppression: true, googEchoCancellation: true, echoCancellation: true, googEchoCancellation2: true, googDAEchoCancellation: true]
> D/FlutterWebRTCPlugin( 3926): MediaStream id: 1f1545c2-aad5-47fe-bb3e-8080d81d92aa
> I/AudioManager( 3926): In isSpeakerphoneOn(), calling application: com.example.new_sip_ua
> I/AudioManager( 3926): In stopBluetoothSco(), calling application: com.example.new_sip_ua
> I/AudioManager( 3926): In setSpeakerphoneOn(), on: true, calling application: com.example.new_sip_ua
> I/flutter ( 3926): call id :dvhv782950259739e1850555843041
> I/org.webrtc.Logging( 3926): EglBase14Impl: Using OpenGL ES version 2
> I/org.webrtc.Logging( 3926): EglRenderer: Initializing EglRenderer
> I/org.webrtc.Logging( 3926): WebRtcAudioRecordExternal: enableBuiltInAEC(true)
> I/org.webrtc.Logging( 3926): WebRtcAudioEffectsExternal: setAEC(true)
> I/org.webrtc.Logging( 3926): WebRtcAudioRecordExternal: enableBuiltInNS(true)
> I/org.webrtc.Logging( 3926): WebRtcAudioEffectsExternal: setNS(true)
> I/org.webrtc.Logging( 3926): NetworkMonitor: Start monitoring with native observer -5476376617324803488 fieldTrialsString: 
> I/org.webrtc.Logging( 3926): NetworkMonitorAutoDetect: Network handle: 553161510925 becomes available: 128
> D/FlutterWebRTCPlugin( 3926): onIceGatheringChangeGATHERING
> I/org.webrtc.Logging( 3926): NetworkMonitorAutoDetect: handle: 553161510925 capabilities changed: [ Transports: WIFI Capabilities: NOT_METERED&INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&VALIDATED&NOT_ROAMING&FOREGROUND&NOT_CONGESTED&NOT_SUSPENDED LinkUpBandwidth>=330179Kbps LinkDnBandwidth>=407628Kbps SignalStrength: -57 AdministratorUids: [] RequestorUid: -1 RequestorPackageName: null]
> I/org.webrtc.Logging( 3926): EglBase14Impl: Using OpenGL ES version 2
> I/org.webrtc.Logging( 3926): NetworkMonitorAutoDetect: handle: 553161510925 link properties changed
> I/org.webrtc.Logging( 3926): EglRenderer: Initializing EglRenderer
> 4
> D/FlutterWebRTCPlugin( 3926): onIceCandidate
> I/chatty  ( 3926): uid=10248(com.example.new_sip_ua) signaling_threa identical 3 lines
> D/FlutterWebRTCPlugin( 3926): onIceCandidate
> I/flutter ( 3926): input => , rule => Request_Response
> I/flutter ( 3926): Format exception: Expected !, %, ', 'ACK', 'BYE', 'CANCEL', 'INVITE', 'NOTIFY', 'OPTIONS', 'REFER', 'REGISTER', 'SUBSCRIBE', *, +, -, ., SIP, _, `, alphanum, ~ but found end of file
> I/flutter ( 3926): [2025-01-27 19:19:08.371] Level.error parser.dart:32 ::: parseMessage() | error parsing first line of SIP message: ""
> I/org.webrtc.Logging( 3926): EglRenderer: Duration: 4010 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
> I/org.webrtc.Logging( 3926): EglRenderer: Duration: 4004 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
> ```

@nikhilingle1302 yea this is an issue ive had before. I havent been able to confirm whether its an issue with the package or an issue specific to my network(and your network)

What this is saying is a message is coming in but its not formatted properly. So it throws it out and doesnt continue, hence why the call doesnt go ahead.

When ive seen it, whats happening is the sip message gets split into two over the network (Maybe its too big)
The first half comes through and the parser sees its correctly formatted.
The second half comes through and it doesnt start with ACK BYE CANCLE etc.. so this error comes up and it chucks it.

This usually goes away and comes back by itself. 

Ive been thinking about writing some sort of buffer or queue. That saves every last message.
If the next method that comes in fails the parses. It checks if its actually the second half of the last message that came in, joins them. Passes it on and everything would carry on fine.

**Comment by nikhilingle1302** [comment]
@mikaelwills Am I unable to make calls due to the error mentioned in the logs?
I am trying to initiate a call, and while the call screen appears in my app (showing [Direction.outgoing]None) ,but  the call is not being received in the other app. What could be the issue?

````

I/FlutterWebRTCPlugin( 3926): getUserMedia(audio): mandatory: [], optional: [googNoiseSuppression: true, googEchoCancellation: true, echoCancellation: true, googEchoCancellation2: true, googDAEchoCancellation: true]
D/FlutterWebRTCPlugin( 3926): MediaStream id: 583c1406-5f74-4c72-8c54-f3110e5385f0
I/org.webrtc.Logging( 3926): WebRtcAudioRecordExternal: enableBuiltInAEC(true)
I/org.webrtc.Logging( 3926): WebRtcAudioEffectsExternal: setAEC(true)
I/org.webrtc.Logging( 3926): WebRtcAudioRecordExternal: enableBuiltInNS(true)
I/org.webrtc.Logging( 3926): WebRtcAudioEffectsExternal: setNS(true)
D/FlutterWebRTCPlugin( 3926): onIceGatheringChangeGATHERING
D/FlutterWebRTCPlugin( 3926): onIceCandidate
I/chatty  ( 3926): uid=10248(com.example.new_sip_ua) signaling_threa identical 1 line
D/FlutterWebRTCPlugin( 3926): onIceCandidate
I/flutter ( 3926): call id :t93ql844046179119290ki4bw89zk1
D/FlutterWebRTCPlugin( 3926): onIceCandidate
I/org.webrtc.Logging( 3926): EglBase14Impl: Using OpenGL ES version 2
I/org.webrtc.Logging( 3926): EglRenderer: Initializing EglRenderer
I/org.webrtc.Logging( 3926): EglBase14Impl: Using OpenGL ES version 2
I/org.webrtc.Logging( 3926): EglRenderer: Initializing EglRenderer
D/FlutterWebRTCPlugin( 3926): onIceCandidate
I/chatty  ( 3926): uid=10248(com.example.new_sip_ua) signaling_threa identical 2 lines
D/FlutterWebRTCPlugin( 3926): onIceCandidate
I/org.webrtc.Logging( 3926): EglRenderer: Duration: 4008 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
2
I/org.webrtc.Logging( 3926): EglRenderer: Duration: 4007 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging( 3926): EglRenderer: Duration: 4005 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging( 3926): NetworkMonitorAutoDetect: handle: 553161510925 capabilities changed: [ Transports: WIFI Capabilities: NOT_METERED&INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&VALIDATED&NOT_ROAMING&FOREGROUND&NOT_CONGESTED&NOT_SUSPENDED LinkUpBandwidth>=220289Kbps LinkDnBandwidth>=407628Kbps SignalStrength: -54 AdministratorUids: [] RequestorUid: -1 RequestorPackageName: null]
3
I/org.webrtc.Logging( 3926): EglRenderer: Duration: 4010 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging( 3926): EglRenderer: Duration: 4006 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging( 3926): EglRenderer: Duration: 4007 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging( 3926): EglRenderer: Duration: 4010 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging( 3926): EglRenderer: Duration: 4006 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging( 3926): EglRenderer: Duration: 4008 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
`
```

**Comment by md-riaz** [comment]
@Kay-coding Hi,
What sip server are you using can you tell?
