### ISSUE TITLE
Initiating a call takes very long on most recent commit

### ISSUE THREAD

**Issue by wilkomanger** [flutter-webrtc/dart-sip-ua#54]
**Describe the bug**
When starting a call, there's a very long delay until the actual call is made. It seems fine at ae529ee5985b7bfb5f04f547e0c3df08defea5ef, but is slow at 46f74b0bbcf468956fb1f40362bca369ae54a54f.

**Expected behavior**
Calls should work quicker, as in previous versions of the library.

**Comment by ghenry** [comment]
Hey @wilkomanger 

Nice to meet you! I love reading your code of Pattle. Nice work! Been following it for a year or so. Now on to BLoC too?

Is this still happening? Can you provide more context?

**Comment by wilkomanger** [comment]
Hey, thanks! Yes Pattle indeed uses flutter_bloc now :)

I don't use this package at the moment anymore, so I don't know if it's still happening. But from what I remember, it took like a minute after calling the method before anything actually happened.

**Comment by ghenry** [comment]
Takes as long as the ice query takes. Where's Pattle gone now?

**Comment by wilkomanger** [comment]
> Where's Pattle gone now?

Unfortunately Pattle is discontinued.

**Comment by ghenry** [comment]
<notifications@github.com> wrote:

> Where's Pattle gone now?
>
> Unfortunately Pattle is discontinued.
>
On no! What happened? Apologies, none of my business.

**Comment by wilkomanger** [comment]
Ha no it's okay, I just lost interest in the project over time, and there are other Matrix clients with more features now (although they do things differently).

**Comment by ghenry** [comment]
Ah, shame! Was great code. Enjoyed reading it. Thought you may have died of
the bloc though :)

**Comment by wilkomanger** [comment]
Thanks! And don't worry, my next TBD is also made with Flutter. And still a fan of bloc haha

**Comment by ghenry** [comment]
Cool. Come over to the GetX side!

**Comment by ghenry** [comment]
BTW, did you make any of your app into a lib for matrix use on pub.dev?

**Comment by wilkomanger** [comment]
Yes: https://pub.dev/packages/matrix_sdk
