### ISSUE TITLE
video call using web variant of example fails - signaling state null 

### ISSUE THREAD

**Issue by markmelling** [flutter-webrtc/dart-sip-ua#71]
I attempted to make a video calling between two clients using the web variant (for both clients) of the example app. 
Freeswitch was used as the SIP/media server.

**To Reproduce**
1. Load app on client A and register with freeswitch server
2. Load app on client B and register with freeswitch server
3. Client A calls (clicking on video icon) client B
4. Client B receives incoming call, click to accept call
5. Call is disconnected

**Expected behavior**
I expected a video call to be established

**System Infomation()**
Flutter 1.14.6
Client A - Chrome (version 81.0.4044.62) running on Pixelbook (chromebook)
Client B - Chrome (version 80.0.3987) running on Android (version 9.0)

Further investigation revealed that it was failing when calling _connection.setRemoteDescription(answer) in rtc_session.dart because the RTCPeerConnection was in the incorrect signaling state (it was null), even though setLocalDescription had been called previously.

I then decided in rtc_session.dart to define a onSignalingState callback:
```
this._connection.onSignalState = (signalingState) {
    print('signalingState $signalingState');
}
```
But to my surprise when I re-ran the video call worked! Which I don't understand at all. I removed this code and re-ran and I was able to repeat the failure, and put the code back and it worked.

The video call was established and working, although there wasn't any audio, but I've not had time to investigate this issue.

**Comment by cloudwebrtc** [comment]
@markmelling Is there any error message printed in the chrome console？

**Comment by markmelling** [comment]
Thanks for the quick response.

The only actual errors in the chrome console are:
```
call failed with cause: Code: [488], Cause: Bad Media Description, Reason: Not Acceptable Here

"peerconnection:setremotedescriptionfailed" [error:InvalidStateError: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: Called in wrong state: kStable]
```
I know from my investigations that the signalling state is actually null when setRemoteDescription is called.

**Comment by cloudwebrtc** [comment]
It looks like a timing issue with PeerConnection API.

**Comment by ghenry** [comment]
Still an issue?

**Comment by ZZXUN233** [comment]
I got the same error.
jssip 3.5.10 in the chrome
dart-sip-ua v0.3.1 in android
from android call to chrome works fine
but from chrome call to android get 488 error
[log1.txt](https://github.com/flutter-webrtc/dart-sip-ua/files/5463205/log1.txt)
