### ISSUE TITLE
Initial call attempt always fails

### ISSUE THREAD

**Issue by matscat** [flutter-webrtc/dart-sip-ua#73]
When I press the green call button it always fails on the first attempt. It times out after 30 seconds or more and then when I press the call button again it usually connects the second time. However it often takes takes three attempts to make the call. The initial call attempt fails every time. Same for other users. We are connecting to a FreeSwitch server from android devices. Latest version of Flutter on the beta channel.

In the logs there is no error message. On both failed and successful attempts the communication process between client and server flows the same up to the point where a "SIP/2.0 100 Trying” message should be received. This is never received on failed attempts.

We would like all calls to connect on the first attempt. Any help would be  appreciated. 
Stack traces of both a failed and a successful attempt are below:

**Stack Trace of a failed attempt:**
I/flutter ( 9792): INVITE sip:101281000@192.xxx.xx.xx SIP/2.0
I/flutter ( 9792): Via: SIP/2.0/WSS 566862440318.invalid;branch=z9hG4bK900689490000000
I/flutter ( 9792): Max-Forwards: 69
I/flutter ( 9792): To: <sip:101281000@192.xxx.xx.xx>
I/flutter ( 9792): From: "XXXX" <sip:127113@192.xxx.xx.xx>;tag=gthy4dc1g3
I/flutter ( 9792): Call-ID: 66amqedxgmtjgpiwl5nj
I/flutter ( 9792): CSeq: 2755 INVITE
I/flutter ( 9792): Proxy-Authorization: Digest algorithm=MD5, username="127113", realm="192.xxx.xx.xx", nonce="a25d752d-b430-40f8-9a11-a4f7875d4d25", uri="sip:101281000@192.xxx.xx.xx", response="c54aca8cfeef309088289b2c854da2bc", qop=auth, cnonce="741545154308", nc=00000001
I/flutter ( 9792): Contact: <sip:16007037@566862440318.invalid;transport=ws;ob>
I/flutter ( 9792): Content-Type: application/sdp
I/flutter ( 9792): Session-Expires: 120
I/flutter ( 9792): Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO
I/flutter ( 9792): Supported: timer,ice,replaces,outbound
I/flutter ( 9792): User-Agent: dart-sip-ua v0.0.1
I/flutter ( 9792): Content-Length: 2033
I/flutter ( 9792): 
I/flutter ( 9792): v=0
I/flutter ( 9792): o=- 651521019053583620 2 IN IP4 127.0.0.1
I/flutter ( 9792): s=-
I/flutter ( 9792): t=0 0
I/flutter ( 9792): a=group:BUNDLE audio
I/flutter ( 9792): a=msid-semantic: WMS 0e87a210-ee77-4813-bdee-e0bfbf
I/flutter ( 9792): [2020-04-04 20:05:32.790] Level.debug websocket_interface.dart:130 ::: send()
I/flutter ( 9792): [2020-04-04 20:05:32.794] Level.debug websocket_dart_impl.dart:44 ::: send: INVITE sip:101281000@192.xxx.xx.xx SIP/2.0
I/flutter ( 9792): Via: SIP/2.0/WSS 566862440318.invalid;branch=z9hG4bK900689490000000
I/flutter ( 9792): Max-Forwards: 69
I/flutter ( 9792): To: <sip:101281000@192.xxx.xx.xx>
I/flutter ( 9792): From: "Shane Walsh" <sip:127113@192.xxx.xx.xx>;tag=gthy4dc1g3
I/flutter ( 9792): Call-ID: 66amqedxgmtjgpiwl5nj
I/flutter ( 9792): CSeq: 2755 INVITE
I/flutter ( 9792): Proxy-Authorization: Digest algorithm=MD5, username="127113", realm="192.xxx.xx.xx", nonce="a25d752d-b430-40f8-9a11-a4f7875d4d25", uri="sip:101281000@192.xxx.xx.xx", response="c54aca8cfeef309088289b2c854da2bc", qop=auth, cnonce="741545154308", nc=00000001
I/flutter ( 9792): Contact: <sip:16007037@566862440318.invalid;transport=ws;ob>
I/flutter ( 9792): Content-Type: application/sdp
I/flutter ( 9792): Session-Expires: 120
I/flutter ( 9792): Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO
I/flutter ( 9792): Supported: timer,ice,replaces,outbound
I/flutter ( 9792): User-Agent: dart-sip-ua v0.0.1
I/flutter ( 9792): Content-Length: 2033
I/flutter ( 9792): 
I/flutter ( 9792): v=0
I/flutter ( 9792): o=- 651521019053583620 2 IN IP4 127.0.0.1
I/flutter ( 9792): s=-
I/flutter ( 9792): t=0 0
I/flutter ( 9792): a=group:BUNDLE audio
I/flutter ( 9792): a=msid-semantic: WMS 0e87a210-ee77-4813-bdee-e0bfbf4ff
I/flutter ( 9792): [2020-04-04 20:05:32.798] Level.debug invite_client.dart:90 ::: Timer D expired for transaction z9hG4bK16565475180000000
I/org.webrtc.Logging( 9792): EglRenderer: Duration: 4011 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging( 9792): EglRenderer: Duration: 4006 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging( 9792): NetworkMonitorAutoDetect: capabilities changed: [ Transports: CELLULAR Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&VALIDATED&NOT_ROAMING&FOREGROUND&NOT_CONGESTED&NOT_SUSPENDED Unwanted:  LinkUpBandwidth>=468Kbps LinkDnBandwidth>=66931Kbps Specifier: <1>]
I/org.webrtc.Logging( 9792): EglRenderer: Duration: 4012 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging( 9792): EglRenderer: Duration: 4006 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging( 9792): EglRenderer: Duration: 4007 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging( 9792): EglRenderer: Duration: 4007 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.

**Stack Trace of a successful attempt:**
I/flutter ( 9792): INVITE sip:101281000@192.xxx.xx.xx SIP/2.0
I/flutter ( 9792): Via: SIP/2.0/WSS 566862440318.invalid;branch=z9hG4bK6247419230000000
I/flutter ( 9792): Max-Forwards: 69
I/flutter ( 9792): To: <sip:101281000@192.xxx.xx.xx>
I/flutter ( 9792): From: "Shane Walsh" <sip:127113@192.xxx.xx.xx>;tag=51hmm76un2
I/flutter ( 9792): Call-ID: 66amq20q5307301s0672
I/flutter ( 9792): CSeq: 3907 INVITE
I/flutter ( 9792): Proxy-Authorization: Digest algorithm=MD5, username="127113", realm="192.xxx.xx.xx", nonce="639367e4-4022-4240-8209-588d681916b2", uri="sip:101281000@192.xxx.xx.xx", response="4e522fb94658355c298ff642ca1f2ff3", qop=auth, cnonce="0xs25q70tf87", nc=00000001
I/flutter ( 9792): Contact: <sip:16007037@566862440318.invalid;transport=ws;ob>
I/flutter ( 9792): Content-Type: application/sdp
I/flutter ( 9792): Session-Expires: 120
I/flutter ( 9792): Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO
I/flutter ( 9792): Supported: timer,ice,replaces,outbound
I/flutter ( 9792): User-Agent: dart-sip-ua v0.0.1
I/flutter ( 9792): Content-Length: 2034
I/flutter ( 9792): 
I/flutter ( 9792): v=0
I/flutter ( 9792): o=- 2335559035282872422 2 IN IP4 127.0.0.1
I/flutter ( 9792): s=-
I/flutter ( 9792): t=0 0
I/flutter ( 9792): a=group:BUNDLE audio
I/flutter ( 9792): a=msid-semantic: WMS 622502e8-8ecc-40dd-8ac0-f717
I/flutter ( 9792): [2020-04-04 20:12:04.754] Level.debug websocket_interface.dart:130 ::: send()
I/flutter ( 9792): [2020-04-04 20:12:04.758] Level.debug websocket_dart_impl.dart:44 ::: send: INVITE sip:101281000@192.xxx.xx.xx SIP/2.0
I/flutter ( 9792): Via: SIP/2.0/WSS 566862440318.invalid;branch=z9hG4bK6247419230000000
I/flutter ( 9792): Max-Forwards: 69
I/flutter ( 9792): To: <sip:101281000@192.xxx.xx.xx>
I/flutter ( 9792): From: "Shane Walsh" <sip:127113@192.xxx.xx.xx>;tag=51hmm76un2
I/flutter ( 9792): Call-ID: 66amq20q5307301s0672
I/flutter ( 9792): CSeq: 3907 INVITE
I/flutter ( 9792): Proxy-Authorization: Digest algorithm=MD5, username="127113", realm="192.xxx.xx.xx", nonce="639367e4-4022-4240-8209-588d681916b2", uri="sip:101281000@192.xxx.xx.xx", response="4e522fb94658355c298ff642ca1f2ff3", qop=auth, cnonce="0xs25q70tf87", nc=00000001
I/flutter ( 9792): Contact: <sip:16007037@566862440318.invalid;transport=ws;ob>
I/flutter ( 9792): Content-Type: application/sdp
I/flutter ( 9792): Session-Expires: 120
I/flutter ( 9792): Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO
I/flutter ( 9792): Supported: timer,ice,replaces,outbound
I/flutter ( 9792): User-Agent: dart-sip-ua v0.0.1
I/flutter ( 9792): Content-Length: 2034
I/flutter ( 9792): 
I/flutter ( 9792): v=0
I/flutter ( 9792): o=- 2335559035282872422 2 IN IP4 127.0.0.1
I/flutter ( 9792): s=-
I/flutter ( 9792): t=0 0
I/flutter ( 9792): a=group:BUNDLE audio
I/flutter ( 9792): a=msid-semantic: WMS 622502e8-8ecc-40dd-8ac0-f717dd2
I/flutter ( 9792): [2020-04-04 20:12:04.762] Level.debug invite_client.dart:90 ::: Timer D expired for transaction z9hG4bK418270180000000
I/flutter ( 9792): [2020-04-04 20:12:04.968] Level.debug websocket_interface.dart:168 ::: Received WebSocket message
I/flutter ( 9792): [2020-04-04 20:12:04.976] Level.debug transport.dart:314 ::: received text message:
I/flutter ( 9792): 
I/flutter ( 9792): SIP/2.0 100 Trying
I/flutter ( 9792): Via: SIP/2.0/WSS 566862440318.invalid;branch=z9hG4bK6247419230000000;received=213.233.132.141;rport=55640
I/flutter ( 9792): From: "XXX" <sip:127113@192.xxx.xx.xx>;tag=51hmm76un2
I/flutter ( 9792): To: <sip:101281000@192.xxx.xx.xx>
I/flutter ( 9792): Call-ID: 66amq20q5307301s0672
I/flutter ( 9792): CSeq: 3907 INVITE
I/flutter ( 9792): User-Agent: FreeSWITCH-mod_sofia/1.8.7+git~20190702T200609Z~6047ebddfc~64bit
I/flutter ( 9792): Content-Length: 0
I/flutter ( 9792): 
I/flutter ( 9792): 
I/flutter ( 9792): [2020-04-04 20:12:05.9] Level.debug rtc_session.dart:2212 ::: receiveInviteResponse()
I/flutter ( 9792): [2020-04-04 20:12:05.16] Level.debug websocket_interface.dart:168 ::: Received WebSocket message
I/flutter ( 9792): [2020-04-04 20:12:05.19] Level.debug transport.dart:314 ::: received text message:
I/flutter ( 9792): 
I/flutter ( 9792): SIP/2.0 200 OK
I/flutter ( 9792): Via: SIP/2.0/WSS 566862440318.invalid;branch=z9hG4bK6247419230000000;received=213.233.132.141;rport=55640
I/flutter ( 9792): From: "Shane Walsh" <sip:127113@192.xxx.xx.xx>;tag=51hmm76un2
I/flutter ( 9792): To: <sip:101281000@192.xxx.xx.xx>;tag=a8memveeN2vUN
I/flutter ( 9792): Call-ID: 66amq20q5307301s0672
I/flutter ( 9792): CSeq: 3907 INVITE
I/flutter ( 9792): Contact: <sip:101281000@192.xxx.xx.xx:5060;transport=udp>
I/flutter ( 9792): User-Agent: FreeSWITCH-mod_sofia/1.8.7+git~20190702T200609Z~6047ebddfc~64bit
I/flutter ( 9792): Accept: application/sdp
I/flutter ( 9792): Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY, PUBLISH, SUBSCRIBE
I/flutter ( 9792): Require: timer
I/flutter ( 9792): Supported: timer, path, replaces
I/flutter ( 9792): Allow-Events: talk, hold, conference, presence, as-feature-event, dialog, line-seize, call-info, sla, include-session-description, presence.winfo, message-summary, refer
I/flutter ( 9792): Session-Expires: 120;refresher=uac
I/flutter ( 9792): Content-Type: application/sdp
I/flutter ( 9792): Content-Disposition: session
I/flutter ( 9792): Content-Length: 888
I/flutter ( 9792): Remote-Party-ID: "101281000" <sip:10128
I/flutter ( 9792): [2020-04-04 20:12:05.41] Level.debug rtc_session.dart:2212 ::: receiveInviteResponse()
I/flutter ( 9792): [2020-04-04 20:12:05.49] Level.debug dialog.dart:110 ::: new UAC dialog created with status CONFIRMED
I/flutter ( 9792): [2020-04-04 20:12:05.53] Level.debug rtc_session.dart:2312 ::: emit "sdp"
D/FlutterWebRTCPlugin( 9792): peerConnectionSetLocalDescription() start
D/FlutterWebRTCPlugin( 9792): peerConnectionSetLocalDescription() end
D/FlutterWebRTCPlugin( 9792): peerConnectionSetRemoteDescription() start
I/org.webrtc.Logging( 9792): WebRtcAudioRecordExternal: enableBuiltInAEC(false)
I/org.webrtc.Logging( 9792): WebRtcAudioEffectsExternal: setAEC(false)
I/org.webrtc.Logging( 9792): WebRtcAudioRecordExternal: enableBuiltInNS(true)
I/org.webrtc.Logging( 9792): WebRtcAudioEffectsExternal: setNS(true)
I/org.webrtc.Logging( 9792): WebRtcAudioTrackExternal: initPlayout(sampleRate=48000, channels=1)
I/org.webrtc.Logging( 9792): WebRtcAudioTrackExternal: byteBuffer.capacity: 960
I/org.webrtc.Logging( 9792): WebRtcAudioTrackExternal: AudioTrack.getMinBufferSize: 7696
I/org.webrtc.Logging( 9792): WebRtcAudioTrackExternal: createAudioTrackOnLollipopOrHigher
I/org.webrtc.Logging( 9792): WebRtcAudioTrackExternal: nativeOutputSampleRate: 48000
I/org.webrtc.Logging( 9792): WebRtcAudioTrackExternal: AudioTrack: session ID: 10633, channels: 1, sample rate: 48000, max gain: 1.0
I/org.webrtc.Logging( 9792): WebRtcAudioTrackExternal: AudioTrack: buffer size in frames: 3848
I/org.webrtc.Logging( 9792): WebRtcAudioTrackExternal: AudioTrack: buffer capacity in frames: 3848
I/org.webrtc.Logging( 9792): VolumeLogger: start@[name=worker_thread - 9830, id=9266]
I/org.webrtc.Logging( 9792): VolumeLogger: audio mode is: MODE_IN_COMMUNICATION
I/org.webrtc.Logging( 9792): WebRtcAudioTrackExternal: startPlayout
I/org.webrtc.Logging( 9792): VolumeLogger: VOICE_CALL stream volume: 3 (max=7)
I/org.webrtc.Logging( 9792): WebRtcAudioTrackExternal: AudioTrackThread@[name=AudioTrackJavaThread, id=9289]
D/FlutterWebRTCPlugin( 9792): onAddTrack
D/FlutterWebRTCPlugin( 9792): peerConnectionSetRemoteDescription() end
I/flutter ( 9792): [2020-04-04 20:12:05.161] Level.debug rtc_session.dart:2833 ::: session accepted
I/flutter ( 9792): [2020-04-04 20:12:05.168] Level.debug rtc_session.dart:2835 ::: emit "accepted"
I/flutter ( 9792): [2020-04-04 20:12:05.173] Level.debug sip_ua_helper.dart:228 ::: call accepted
I/flutter ( 9792): [2020-04-04 20:12:05.178] Level.debug rtc_session.dart:1211 ::: sendRequest()
I/flutter ( 9792): [2020-04-04 20:12:05.187] Level.debug transport.dart:167 ::: send()
I/flutter ( 9792): [2020-04-04 20:12:05.190] Level.debug transport.dart:178 ::: sending message:
I/flutter ( 9792): 
I/flutter ( 9792): ACK sip:101281000@192.xxx.xx.xx:5060;transport=udp SIP/2.0

**Comment by thelittlebug** [comment]
i think i may be affected from the same bug. things i found out:
1. if i start the call with `helper.call('0043xxxx', false);` eg. with video support, then the first call works.
2. if i start the call with 'helper.call('0043xxx', true)';` eg. without video, the i have the same issues as you

BUT

3. if i start the call with 'helper.call('0043xxx', false);' and modify line 270 in rtc_session.dart to `Map<String, dynamic> mediaConstraints = {'audio': true, 'video': false};` eg. without video it works too!

so there is some sort of side effect. maybe a race condition in the sip handling.

**Comment by ghenry** [comment]
Still getting this?

**Comment by simon-twonary** [comment]
still happening with v0.2.0

**Comment by markmelling** [comment]
I am experiencing the same as @thelittlebug. i.e. calls with video support working and those without failing. I also made the same change - setting video: false in rtc_session and this worked.

With the failing version, on the FreeSwitch end the sip INVITE with Proxy-Authorization never appears in the log and FreeSwitch times out.

I did notice that the message length for the sip INVITE with Proxy-Authorization was a lot longer when video support was included (over 6k) where as with audio only was < 3k. As an experiment I increased the size of the message, by adding spaces to the end and this did seem to make it work. Is it possible there is some buffering going on which is why the smaller (audio only) message is not sent?

**Comment by thelittlebug** [comment]
and this is now fixed?

**Comment by ormoyal** [comment]
no.. still getting the same error, dart-sip-ua 0.5.0

**Comment by cloudwebrtc** [comment]
I learned from multiple developer feedback that this issue seems to be related to FreeSwitch's Websocketer over TLS bug. Sometimes wss message sending and receiving will become very slow or even blocked. You can try to modify it to ws instead of wss (not tls).

**Comment by cloudwebrtc** [comment]
or use opensips as front proxy
