### ISSUE TITLE
Flutter build apk crash on phone

### ISSUE THREAD

**Issue by mohseni676** [flutter-webrtc/dart-sip-ua#78]
I finish development of app and it work fine in debug mode but when build apk for release after installing on phone app crash and didn't open,how to fix it???

**Comment by cloudwebrtc** [comment]
Please refer to the differences below to modify your android project, this should be an android build setup issue.
https://github.com/cloudwebrtc/flutter-webrtc/commit/4966ab01bf256ce27f9d32b96a4768100e9e664e

**Comment by mohseni676** [comment]
my problem didn't solved by this changes, even on cloning example project and change and applying this change crash problem didn't solved,you can try by yourself

**Comment by mohseni676** [comment]
Please answer me
This is my code and made all corrections
But released apk crash after open on multiple and different devices 
https://github.com/mohseni676/madadkar_online

**Comment by ghenry** [comment]
Nobody has to answer you. This is an open source project of volunteers.
Don't be so rude.

**Comment by ghenry** [comment]
How are you getting on @mohseni676
