### ISSUE TITLE
iceServers 

### ISSUE THREAD

**Issue by anasvp444** [flutter-webrtc/dart-sip-ua#79]
Is there any way to change  ice Servers. my audio is one way. No audio in chrome side and echo back in other side.

**Comment by olegshentz1** [comment]
Hello @ghenry, @cloudwebrtc 

I have the same issue. There is no audio in chrome browser. I tried to add more iceServer like this:
'pcConfig': {
        'iceServers': [
          {'url': 'stun:stun.l.google.com:19302'},
          {'url': 'stun:stun4.l.google.com:19302'},
          {'url': 'stun:iphone-stun.strato-iphone.de:3478'},
          {'url': 'stun:numb.viagenie.ca:3478'},
          {'url': 'stun:s1.taraba.net:3478'},
          /*
           * turn server configuration example.
            {
              'url': 'turn:123.45.67.89:3478',
              'username': 'change_to_real_user',
              'credential': 'change_to_real_secret'
            },
          */
        ]
      },

but it did not work.
Are there any suggestions how to fix this issue ?

Thanks in advance.

**Comment by anasvp444** [comment]
Video call is okay. I got two-directional audio. but echo in both ends disturbing me.

**Comment by anasvp444** [comment]
I got two side audio when call with video.

**Comment by sergeynekrasov8430** [comment]
Hallo !!!   And can I tell you how and where you can completely turn off access to the ICE server?

**Comment by ghenry** [comment]
What's on the Chrome side?

**Comment by sergeynekrasov8430** [comment]
I don’t use Chrome side ..., I'm trying to assemble everything for iOS

**Comment by simon-twonary** [comment]
same issue here. On Audio Call is one way only, but working fine(audio and video) on Video Call.
