### ISSUE TITLE
outgoing call got failed and redirect to dailpad screen 

### ISSUE THREAD

**Issue by mahmoud-adnan** [flutter-webrtc/dart-sip-ua#82]
**Describe the bug**
When i try to call any device (mobile or web), outgoing device got redirected to home with call state failed. it works fine if the same device is incoming call.
**To Reproduce**
1. From device 1, try to voice call device2
2. See Log.
3. Device 1 redirected to dailpad screen.
4. Device 2 working fine.

**Expected behavior**
State for device 1 changed to confirmed instead of failed in order to open call view.

**System Infomation()**
Flutter SDK Version: happened on master, beta and dev channels 
Target OS and Version: Android and iOS
Host OS and Version:

**Comment by ghenry** [comment]
Hi @mahmoud-adnan 

Is this an issue on our side or a SIP issue? For two other devices on the same network with same creds, do the calls work?

Thanks.
