### ISSUE TITLE
SDK version

### ISSUE THREAD

**Issue by jason-shen** [flutter-webrtc/dart-sip-ua#86]
firstly thanks for the great lib, i just got a quick question,
will this build on the stable flutty sdk channel
or is it strictly on dev channel

thanks

**Comment by ghenry** [comment]
Did you try stable?

**Comment by jason-shen** [comment]
> Did you try stable?

no i haven't tried

**Comment by cloudwebrtc** [comment]
@jason-shen Using stable will only work on mobile, dev channel supports macos and web
