### ISSUE TITLE
RFC8599 support 

### ISSUE THREAD

**Issue by ghenry** [flutter-webrtc/dart-sip-ua#89]
OpenSIPS has just added this. Amazing. Do we need anything on the UA I wonder. 

https://www.linkedin.com/posts/opensips_opensips31-release-opensource-activity-6670654698992795648-qaJn

https://tools.ietf.org/html/rfc8599

**Comment by ghenry** [comment]
https://blog.opensips.org/2020/05/07/sip-push-notification-with-opensips-3-1-lts-rfc-8599-supportpart-i/amp/

**Comment by cloudwebrtc** [comment]
Nice feature, Looks indispensable for mobile.

**Comment by ghenry** [comment]
Can't run in production really without it.

**Comment by ghenry** [comment]
Just starting this now, and it appears everything that we need is already in place. We just need to expose (like with did with `ha1`) the `_extraHeaders` and `_extraContactParams` in `lib/src/registrator.dart`

then we pass in these in `_extraContactParams`:

```
       pn-provider=acme;
       pn-param=acme-param;
       pn-prid=ZTY4ZDJlMzODE1NmUgKi0K>;
```

so just:

```
settings.extraContactParams = <String, String>{
       'pn-provider': 'fcm',
       'pn-param': 'fcm-custom-param',
       'pn-prid': 'ZTY4ZDJlMzODE1NmUgKi0K' // the Project ID which is available in the Firebase console Settings pane. Not sure on APN (Apple version yet)
}
helper.start(settings);
```

actually just `ContactParams` but might as well expose `_extraHeaders`. We'll be making:

```
Example of a SIP REGISTER request including a 'sip.pnsreg'
     media feature tag:

     REGISTER sip:alice@example.com SIP/2.0
     Via: SIP/2.0/TCP alicemobile.example.com:5060;branch=z9hG4bKnashds7
     Max-Forwards: 70
     To: Alice <sip:alice@example.com>
     From: Alice <sip:alice@example.com>;tag=456248
     Call-ID: 843817637684230@998sdasdh09
     CSeq: 1826 REGISTER
     Contact: <sip:alice@alicemobile.example.com;
       pn-provider=acme;
       pn-param=acme-param;
       pn-prid=ZTY4ZDJlMzODE1NmUgKi0K>;
       +sip.pnsreg
     Expires: 7200
     Content-Length: 0
```

as per https://tools.ietf.org/html/rfc8599#page-11

**Comment by ghenry** [comment]
Sorry for FCM its:

```

   The value of the 'pn-provider' URI parameter is "fcm".

   The value of the 'pn-param' URI parameter is the Project ID.

   The value of the 'pn-prid' URI parameter is the Registration token,
   which is generated by the FCM SDK for each client app instance.
```

and Apple:

https://tools.ietf.org/html/rfc8599#page-30

**Comment by ghenry** [comment]
@cloudwebrtc What's the best way to expose `  setExtraContactParams(extraContactParams) {` in https://github.com/cloudwebrtc/dart-sip-ua/blob/master/lib/src/registrator.dart#L92 to `helper.start(settings);` ?

**Comment by cloudwebrtc** [comment]
@ghenry maybe we can add `RegisterParams` into UaSettings.

```dart
class RegisterParams {
  Map<String, dynamic> extraHeaders = {};
  Map<String, dynamic> extraContactParams = {};
}

class UaSettings {
  String webSocketUrl;
  WebSocketSettings webSocketSettings = WebSocketSettings();

  RegisterParams registerParams = RegisterParams();
  ...
}
```

**Comment by ghenry** [comment]
I'll check the spec to see if they are need elsewhere too. But this looks
good.

**Comment by ghenry** [comment]
Yep, checked the RFC and these only need to be in the REGISTER request, so we can start there and expand if anyone ever needs to add headers for anything else (like an INVITE?):

https://tools.ietf.org/html/rfc8599#section-4.1

Thanks.

**Comment by ghenry** [comment]
@cloudwebrtc Did you have any more thoughts on this? Want me to do this and submit a PR?

**Comment by cloudwebrtc** [comment]
@ghenry If you can submit a PR, it would be great. I don't have a complete push test environment, so the implementation of RFC8599 is a bit difficult for me. If you need my help, please send me a message.

**Comment by ghenry** [comment]
On it now.

**Comment by ghenry** [comment]
Done. PR coming.

**Comment by ghenry** [comment]
Apologies. I totally messed that up. I though I was in a forked repo, but I was in master here.

**Comment by ghenry** [comment]
Want me to revert and do it properly?

**Comment by ghenry** [comment]
This should be a List too:

https://github.com/cloudwebrtc/dart-sip-ua/blob/cb23a4c1243c7295b25c66a100dd7290aaca5808/lib/src/sip_ua_helper.dart#L538

**Comment by cloudwebrtc** [comment]
Yes, you can copy the changes to the branch and merge after functional verification. I think RFC8599 should have many changes.

**Comment by ghenry** [comment]
So we prefer branch based pull requests versus forks?

All I've really done is expose existing functionality for these extra
params and headers.

If we want RFC8599 then we need to validate params and a few other things
but that seems like duplicate effort when all we need are these extra
params.

I'll read again to see if there is anything else we need, but I have all I
need now.

Thanks.

**Comment by ghenry** [comment]
My original design was something like rfc8599-mode: true or similar and then we pass in the the required fields client side (the user of this project does) and we add any other bits. The issue is a lot of the RFC is to be done client side outside the SIP bit. Wake ups, getting your token etc.

I have this at the moment which is working client side (I use GetX which provides `GetPlatform` util in our app for state and tons of other things):

```
    if (GetPlatform.isAndroid || GetPlatform.isWeb) {
      settings.registerParams.extraContactParams = <String, String>{
        'pn-provider': 'fcm',
        'pn-param': FCM_PROJECT_ID,
        'pn-prid': _fcmToken
      };
    } else {
      settings.registerParams.extraContactParams = <String, String>{
        'pn-provider': 'apns',
        'pn-param': APPLE_BUNDLE_ID_VOIP,
        'pn-prid': _apnsToken
      };
    }
    helper.start(settings);https://tools.ietf.org/html/rfc8599#section-4
```

You need to use PushKit and CallKit on iOS for background VoIP notifications - https://developer.apple.com/documentation/pushkit/responding_to_voip_notifications_from_pushkit

Then a lot of other headers you can add depending on what you (as the project user) have implemented in your app.

https://tools.ietf.org/html/rfc8599#section-4 discusses all the client has to do which is the users choice and controlled by Contact Params on REGISTER.

Me having exposed the existing functionality to add these headers using your advice, is all I think is needed at the moment. I am in control of the SIP proxy though, so those that aren't and are navigating the RFC may have other ideas for things the project can do behind the scenes to help out, but I think this is enough. I think if you were writing a generic softphone to be sold on the app store you'd look to do more queries and RFC things to "query if Push is support" etc. They are just headers though you add and remove.

Ultimately, what I've done has nothing to do with RFC8599 though. Just headers and params :-)

I'll revert the changes and put in a brand for a PR. Apologies for that mistake. I though I was in a forked repo.

**Comment by ghenry** [comment]
This is all wrong :-(

They are supposed to be INSIDE the Contact URI. They should Contact URI params, not header params

So as per RFC:

```
     Contact: <sip:alice@alicemobile.example.com;
       pn-provider=acme;
       pn-param=acme-param;
       pn-prid=ZTY4ZDJlMzODE1NmUgKi0K>;
       +sip.pnsreg
```

where as we've exposed them outside `<>;pn-provider`

Time to rethink. It would need to be done here:

https://github.com/cloudwebrtc/dart-sip-ua/blob/master/lib/src/ua.dart#L58

Thoughts? Ideas?

**Comment by ghenry** [comment]
So we have a plan at https://github.com/versatica/JsSIP/issues/656#issuecomment-668421253

I'll do the same here and leave the Registerar headers and params exposed.

Can you review that PR @cloudwebrtc

**Comment by ghenry** [comment]
I did see two Contact header lines at one point though. Will check that.

**Comment by cloudwebrtc** [comment]
@ghenry I read RFC8599 again and came to the following conclusion:

Take this message header as an example
```
Contact: <sip:alice@alicemobile.example.com;
       pn-provider=acme;
       pn-param=acme-param;
       pn-prid=ZTY4ZDJlMzODE1NmUgKi0K>;
       +sip.pnsreg
Feature-Caps: *;+sip.pns="acme";+sip.pnsreg="121"
```

1,
```
       pn-provider=acme;
       pn-param=acme-param;
       pn-prid=ZTY4ZDJlMzODE1NmUgKi0K
```
The parameters are the params of the Contact URI, and you need to set the parameters for the Uri object.
https://github.com/cloudwebrtc/dart-sip-ua/blob/9fe59ddce566068e92122d69ac3e36878025e85c/lib/src/uri.dart#L89
They are inside the'<>', we can use `Map<String, String>`

2,
```
;+sip.pnsreg
```
 This parameter is extraContactParams, so it is separated by `;` after the contact URI. we can use `Map<String, String>`


3,
```
Feature-Caps: *;+sip.pns="acme";+sip.pnsreg="121"
```
And the last parameter is an extra SIP Header, we can use `List<String>` or `Map<String, String>` package.

**Comment by ghenry** [comment]
Yep, 2 and 3 are the users choice (user of dart-sip-ua), they might not want to use Push to be woken up. They are also now exposed with that PR I did.

We can't really help out users here apart from allowing them to get these things and it depends on their own app.

Did you see how JsSIP thought to do this? I think that makes more sense and is consistent with the params and headers in the PR:

https://github.com/versatica/JsSIP/issues/656#issuecomment-668421253

**Comment by ghenry** [comment]
I'm going to do it like JsSIP suggest:

https://github.com/versatica/JsSIP/issues/656#issuecomment-668421253

Shall I do it in my existing branch?

**Comment by cloudwebrtc** [comment]
@ghenry yeah, no problem.

**Comment by ghenry** [comment]
@cloudwebrtc The problem is we don't have a `contact.uri.clearParams();` or `contact.uri.setParam(key, value);` and we're hard coding things in here:

https://github.com/cloudwebrtc/dart-sip-ua/blob/92291041a01bff3eddb1cc62625441b516503de8/lib/src/registrator.dart#L63

inside:

https://github.com/cloudwebrtc/dart-sip-ua/blob/92291041a01bff3eddb1cc62625441b516503de8/lib/src/ua.dart#L58

then we add additional things to `this._contact` in `registrator.dart`.

Would you like to pass in `ua.configuration.register_extra_contact_uri_params` like so:

```
    // Contact header.
    this._contact = this._ua.contact.toString(ua.configuration.register_extra_contact_uri_params);
```

and handle this there or create a URI Class?

If the former, I'd like to add the extra contact URI params here:

https://github.com/cloudwebrtc/dart-sip-ua/blob/92291041a01bff3eddb1cc62625441b516503de8/lib/src/ua.dart#L72

like 

```
contactUriParams.forEach((param_key, param_value) {
      contact += (';${param_key}');
      if (param_value != null) {
        contact += ('=${param_value}');
      }
    });
```

as they need to live inside the `<>`:

Thanks.

**Comment by ghenry** [comment]
Actually, we do have all we need: https://github.com/cloudwebrtc/dart-sip-ua/blob/master/lib/src/uri.dart

I think https://github.com/cloudwebrtc/dart-sip-ua/blob/92291041a01bff3eddb1cc62625441b516503de8/lib/src/ua.dart#L55 should be a uri object, no?

**Comment by ghenry** [comment]
This this is easy https://github.com/versatica/JsSIP/issues/656#issuecomment-668421253

**Comment by chikondot** [comment]
hello, 

so I have implemented RFC8599 using firebase_messaging.
have got REGISTER being sent when application in background, but failing to still see incoming INVITE.

my assumption is that application should then come to foreground for INVITE to come through? (failing to do so here)
or how should I implement the logic within app? (if anyone has done it before).

regards.

**Comment by DeviArunaMurugan** [comment]
@ghenry , Any idea on this?
https://github.com/flutter-webrtc/dart-sip-ua/issues/389
